<?php
try {
  $myTabla = new OdaTable();
  $myTabla->setCaption('Datos del Acudiente');
  
  $nota = '<br><p>Diligencie lo demás campos, sólo si el acudiente es diferente a padre o madre</p>';
  $myTabla->addRow([
    $frmDataEstud->getSelect(field:'tipo_acudi', data: TipoAcudiente::toArray()),
    $nota,
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput('acudiente'),
    $frmDataEstud->getInput('parentesco'),
  ]);
  
  $myTabla->addRow([
    $frmDataEstud->getInput('acudi_id'),
    $frmDataEstud->getInput('acudi_dir'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput('acudi_tel_1'),
    $frmDataEstud->getInput('acudi_email'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput('acudi_lugar_tra'),
    $frmDataEstud->getInput('acudi_ocupa'),
  ]);

  $myTabla->addRow([
    //$frmDataEstud->getInput('acudi_tiempo_ser'),
    '',
  ]);

  $myTabs->addTab('acudi', 'Acudiente', $myTabla);
  
} catch (\Throwable $th) {
  OdaFlash::error($th);
}
