<?php
  $myTabla = new OdaTable();
  
  $myTabla->addRow([
    $frmEstud->getDataLabel('direccion'), 
    $frmEstud->getDataLabel('barrio'), 
  ]);
  
  $myTabla->addRow([
    $frmEstud->getDataLabel('telefono1'), 
    $frmEstud->getDataLabel('email'),
  ]);

  $myTabla->addRow([
    $frmEstud->getDataLabel('email_instit'),
    $frmEstud->getDataLabel('clave_instit'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getDataLabel('religion'),
    $frmDataEstud->getDataLabel('observacion'),
  ]);

  $myTabs->addTab('ubica', 'Ubicación', $myTabla);