<div class="w3-panel">
    <?= View::Encab(page_module: $controller_name, page_action: $page_action, breadcrumb: $breadcrumb); ?>
    <?= View::flash(); ?>
</div>
<div class="w3-container">
  <?php
    echo 'CUADROS DE HONOR:<br>';
    $periodo_limite = Config::get('config.academic.periodo_actual');
    for ($p=1; $p<=$periodo_limite; $p++) { 
      if (31==$user_id or 1==$user_id) { // primaria
        echo (new Nota)::lnkCuadroHonorPrimariaPDF($p).'&nbsp;';
      }

      if (19==$user_id or 1==$user_id) { // primaria
        echo (new Nota)::lnkCuadroHonorBachilleratoPDF($p).'&nbsp;';
      }
    }
    
    
    for ($p=1; $p<=$periodo_limite; $p++) { 
      if (31==$user_id or 1==$user_id) { // primaria
        echo (new Nota)::lnkCuadroHonorGeneralPrimariaPDF($p).'&nbsp;';
      }

      if (19==$user_id or 1==$user_id) { // primaria
        echo (new Nota)::lnkCuadroHonorGeneralBachilleratoPDF($p).'&nbsp;';
      }
    }
  ?>
    <div  class="w3-bar">
        <?php 
        foreach ($data as $key => $salon) {
            echo "<div id=\"btn-$key\" onclick=\"traer_data($salon->id)\" class=\"w3-bar-item\">$salon</div>" ;
        }
        ?>
    </div>
    
    <h2 id="salon"></h2>
    <div id="spinner"><i class="fa fa-spinner w3-spin" style="font-size:32px"></i></div>
    <div id="resultados">
    </div>

</div>

  <!-- BEGIN BASE JS -->
  <?php
  echo Tag::js(src: 'coordinador/consolidado_notas_fetch', cache: false);
  ?>  

