<div class="w3-panel">
    <?= View::Encab(page_module: $controller_name, page_action: $page_action, breadcrumb: $breadcrumb); ?>
    <?= View::flash(); ?>
</div>
<div class="w3-panel">
    <div  class="w3-bar">
        <?php 
        foreach ($data as $key => $salon) {
            echo "<div id=\"salon-$salon->id\" onclick=\"traer_data($salon->id)\" class=\"w3-bar-item\">$salon</div>" ;
        }
        ?>
    </div>
    
    <h2 id="salon"></h2>
    <div id="resultados">
    </div>

</div>

  <!-- BEGIN BASE JS -->
  <?php
  echo Tag::js(src: 'coordinador/consolidado_notas_fetch', cache: false);
  ?>  

