<?php
  $myTabla = new OdaTable();
  $myTabla->setCaption('Datos del Acudiente');
  
  $nota = '<br><p>Diligencie lo demás campos, sólo si el acudiente es diferente a padre o madre</p>';
  $myTabla->addRow([
    $frmDataEstud->getInput(field:'tipo_acudi'),
    $nota,
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'acudiente'),
    $frmDataEstud->getInput(field:'parentesco'),
  ]);
  
  $myTabla->addRow([
    $frmDataEstud->getInput(field:'acudi_id'),
    $frmDataEstud->getInput(field:'acudi_dir'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'acudi_tel_1'),
    $frmDataEstud->getInput(field:'acudi_email'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'acudi_lugar_tra'),
    $frmDataEstud->getInput(field:'acudi_ocupa'),
  ]);

  $myTabla->addRow([
    //$frmDataEstud->getInput(field:'acudi_tiempo_ser'),
    '',
  ]);

  $myTabs->addTab('acudi', 'Info Acudiente', $myTabla);