<?php
  $myTabla = new OdaTable();

  $myTabla->addRow([
    $frmEstud->getInput(field:'mes_pagado'),
    $frmEstud->getInput(field:'annio_pagado'),
  ]);

  $myTabla->addRow([
    $frmEstud->getInput(field:'is_debe_preicfes'),
    $frmEstud->getInput(field:'is_debe_almuerzos'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'deudor'),
    $frmDataEstud->getInput(field:'codeudor'),
    $frmDataEstud->getInput(field:'codeudor_cc'),
  ]);
  
  $myTabla->addRow([
    $frmDataEstud->getInput(field:'resp_pago_ante_dian'),
    '',
  ]);

  $myTabla->addRow([
    $frmEstud->getInput(field:'contabilidad_id'),
    '',
  ]);

  $myTabs->addTab('conta', 'Contabilidad', $myTabla);

/*
echo _Tag'p.t_medium_azul', "Datos Varios");
$tabla = _open('table', array('width'=>'100%'))
 ._Tag'tr', '<td colspan="2"><b><u>INFORMACIÓN SOBRE EL PAGARÉ</u></b></td>')
 ._Tag'tr', $form->getColCampo('Datosestud/deudor'))


 ._Tag'tr', '<td colspan="2"><b><u>RESPONSABLE ANTE LA DIAN</u></b></td>'
 			 .$form->getColCampo('Datosestud/codeudor'))
 ._Tag'tr', $form->getColCampo('Datosestud/resp_pago_ante_dian,Datosestud/codeudor_cc'))
 
 ._close('table');
echo $tabla;
*/