<?php
$myTabla1 = new OdaTable();
$myTabla1->addRow([
  $frmEstud->getSelect(field:'grado_mat', data: (new Grado)::getGradosArray() ),
  $frmEstud->getSelect(field:'salon_id', data: (new Salon)::getSalonesArray() ),
  '',
]);
$myTabla1->addRow([
  $frmEstud->getCheck(field:'is_habilitar_mat'),
  $frmEstud->getInput(field:'numero_mat'),
]);
$myTabla1->addRow([
  $frmEstud->getInput(field:'annio_promovido'),
  $frmEstud->getSelect(field:'grado_promovido', data: (new Grado)::getGradosArray() ),
]);
  
$myTabla2 = new OdaTable();
$myTabla2->addRow([
  '1. '.$modelAdjuntos->getLinkArchivo(1),
]);
$myTabla2->addRow([
  '2. '.$modelAdjuntos->getLinkArchivo(2),
]);
$myTabla2->addRow([
  '3. '.$modelAdjuntos->getLinkArchivo(3),
]);
$myTabla2->addRow([
  '4. '.$modelAdjuntos->getLinkArchivo(4),
]);
$myTabla2->addRow([
  '5. '.$modelAdjuntos->getLinkArchivo(5),
]);
$myTabla2->addRow([
  '6. '.$modelAdjuntos->getLinkArchivo(6),
]);

$lnk_subir_adjuntos = '<br>'.OdaTags::linkButton("secretaria/subirAdjuntosMatricula/{$modelEstud->id}", 'subir archivos');

$lnk_docs_mat = '<br>'.OdaTags::linkButton(
  action: "admin/estudiantes/exportDocsMatricula/{$modelEstud->id}", 
  text: 'Descargar Documentos Mat', 
  attrs: 'class="w3-button w3-green" target="_blank"'
);


$myTabs->addTab('matri', 'Matrícula', $myTabla1.'<br><hr>'.$myTabla2."<br>$lnk_subir_adjuntos<br>$lnk_docs_mat");

