<?php
  $myTabla = new OdaTable();

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'padre'),
    $frmDataEstud->getInput(field:'padre_id'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'padre_tel_1'),
    $frmDataEstud->getInput(field:'padre_tel_2'),
  ]);
  
  $myTabla->addRow([
    $frmDataEstud->getInput(field:'padre_dir'),
    $frmDataEstud->getInput(field:'padre_email'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'padre_ocupa'),
    $frmDataEstud->getInput(field:'padre_lugar_tra'),
  ]);

  $myTabla->addRow([
    $frmDataEstud->getInput(field:'padre_tiempo_ser'),
    '',
  ]);

  $myTabs->addTab('padre', 'Padre', $myTabla);
