<div class="w3-container">
   <?= View::flash().View::Encab($controller_name, $page_action, '') ?>
</div>

<div class="w3-container">
   <?php 
    $Usuario = (new Empleado())::get($user_id);
    $tabla = new OdaTable();
    $tabla->addRow(data: ['Empleado', $Usuario->getNombreCompleto() ]);
    $tabla->addRow(data: ['Username', $Usuario->username ]);
    $tabla->addRow(data: ['Documento', $Usuario->documento ]);
    $tabla->addRow(data: ['MS TEAMS', $Usuario->getCuentaInstit() ]);
    $tabla->addRow(data: ['Direccion', $Usuario->direccion ]);
    $tabla->addRow(data: ['Email', $Usuario->email ]);
    $tabla->addRow(data: ['Teléfono', $Usuario->telefono1 ]);
    echo $tabla;
   ?>
</div>
