<footer class="w3-margin-top">
</footer>

<?= tag::js(src: "tabs_h");?>

<script>
  // sincronizar inputs (definitiva) con ranges.
  const ranges = document.querySelectorAll('input[type="range"]');
  const valores = document.querySelectorAll('input[type="number"][id*="notas_definitiva"]');
  for (let i = 0; i < ranges.length; i++) {
    ranges[i].addEventListener('input', (event) => {
      valores[i].value = event.target.value;
    });
  }
  
  for (let i = 0; i < valores.length; i++) {
    valores[i].addEventListener('input', (event) => {
      ranges[i].value = event.target.value;
    });
  }
  

  const min_f = document.getElementById('min_f').innerHTML.trim();
  const max_f = document.getElementById('max_f').innerHTML.trim();
  const min_d = document.getElementById('min_d').innerHTML.trim();
  const max_d = document.getElementById('max_d').innerHTML.trim();
  const min_r = document.getElementById('min_r').innerHTML.trim();
  const max_r = document.getElementById('max_r').innerHTML.trim();

  const inputs = document.querySelectorAll('.color-input');
  inputs.forEach(input => {
    input.addEventListener('input', () => {
      const num = parseInt(input.value);
      if (num >= min_f && num <= max_f) {
        input.style.color = 'green';
      } else if (num >= min_d && num <= max_d) {
        input.style.color = 'blue';
      } else if (num >= min_r && num <= max_r) {
        input.style.color = 'red';
      } else {
        input.style.color = 'black';
      }
    });
  });

</script>