<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title> <?=$page_title?> </title>
    <meta property="og:title" content="<?=$page_action?>">
    <meta name="author" content="<?=Config::get('config.construxzion.name')?>">
    <meta property="og:locale" content="en_ES">
    <meta name="description" content="<?=Config::get('config.construxzion.app_description')?>">
    <meta property="og:description" content="<?=Config::get('config.construxzion.app_description')?>">
    <link rel="canonical" href="<?=PUBLIC_PATH?>">
    <meta property="og:url" content="<?=PUBLIC_PATH?>">
    <meta property="og:site_name" content="<?=APP_NAME.' - '.Config::get('config.construxzion.name')?>">

    
    <!-- FAVICONS -->
    <link rel="apple-touch-icon" sizes="144x144" href="<?=PUBLIC_PATH?>assets/apple-touch-icon.png">
    <link rel="shortcut icon" href="<?=PUBLIC_PATH?>assets/favicon.ico">
    <meta name="theme-color" content="#3063A0"><!-- End FAVICONS -->
    <!-- GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600" rel="stylesheet"><!-- End GOOGLE FONT -->
    <!-- BEGIN PLUGINS STYLES -->
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/vendor/open-iconic/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/vendor/@fortawesome/fontawesome-free/css/all.min.css"><!-- END PLUGINS STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/stylesheets/theme.min.css" data-skin="default">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/stylesheets/theme-dark.min.css" data-skin="dark">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/stylesheets/custom.css">
    <script>
      var skin = localStorage.getItem('skin') || 'default';
      var isCompact = JSON.parse(localStorage.getItem('hasCompactMenu'));
      var disabledSkinStylesheet = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');
      // Disable unused skin immediately
      disabledSkinStylesheet.setAttribute('rel', '');
      disabledSkinStylesheet.setAttribute('disabled', true);
      // add flag class to html immediately
      if (isCompact == true) document.querySelector('html').classList.add('preparing-compact-menu');
    </script><!-- END THEME STYLES -->
  </head>
  <body>

    <!-- .app -->
    <div class="app">
      <!--[if lt IE 10]>
      <div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
      <![endif]-->

      <!-- .app-header -->
      <header class="app-header app-header-dark">
        <!-- .top-bar -->
        <div class="top-bar">
          <!-- .top-bar-brand -->
          <div class="top-bar-brand">
            <!-- toggle aside menu -->
            <a href="<?=PUBLIC_PATH?>admisiones">
            <?=OdaTags::img(src: 'logo.png', attrs:'style="width:200px"')?>
            </a>
          </div><!-- /.top-bar-brand -->
        </div><!-- /.top-bar -->
      </header><!-- /.app-header -->

      <!-- .app-main -->
      <main class="app-main">
        <!-- .wrapper -->
        <div class="wrapper">
          <?php View::content() ?>
        </div>
        <!-- /.wrapper -->
      </main><!-- /.app-main -->
    </div><!-- /.app -->

  </body>
</html>