<!DOCTYPE html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><!-- End Required meta tags -->
    
    <!-- Begin SEO tag -->
    <title><?=$page_title?></title>
    <meta property="og:title" content="Index">
    <meta name="author" content="<?=Config::get('config.construxzion.name')?>">
    <meta property="og:locale" content="es_ES">
    <meta name="description" content="<?=Config::get('config.construxzion.app_description')?>">
    <meta property="og:description" content="<?=Config::get('config.construxzion.app_description')?>">
    <link rel="canonical" href="<?=PUBLIC_PATH?>">
    <meta property="og:url" content="<?=PUBLIC_PATH?>">
    <meta property="og:site_name" content="<?=APP_NAME.' - '.Config::get('config.construxzion.name')?>">

    <!-- FAVICONS -->
    <link rel="apple-touch-icon" sizes="144x144" href="<?=PUBLIC_PATH?>assets/apple-touch-icon.png">
    <link rel="shortcut icon" href="<?=PUBLIC_PATH?>assets/favicon.ico">
    <meta name="theme-color" content="#3063A0"><!-- End FAVICONS -->
    <!-- GOOGLE FONT -->
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600" rel="stylesheet"><!-- End GOOGLE FONT -->
    <!-- BEGIN PLUGINS STYLES -->
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/vendor/open-iconic/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/vendor/@fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/vendor/flatpickr/flatpickr.min.css"><!-- END PLUGINS STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/stylesheets/theme.min.css" data-skin="default">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/stylesheets/theme-dark.min.css" data-skin="dark">
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>assets/stylesheets/custom.css">
    <script>
      var skin = localStorage.getItem('skin') || 'default';
      var isCompact = JSON.parse(localStorage.getItem('hasCompactMenu'));
      var disabledSkinStylesheet = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');
      // Disable unused skin immediately
      disabledSkinStylesheet.setAttribute('rel', '');
      disabledSkinStylesheet.setAttribute('disabled', true);
      // add flag class to html immediately
      if (isCompact == true) document.querySelector('html').classList.add('preparing-compact-menu');
    </script><!-- END THEME STYLES -->
  </head>

  <body>
    <?php $image_profile=IMG_UPLOAD_PATH.'users/32754582.png'; ?>
    <div class="app has-fullwidth">
      <?php View::partial("looper/header", params: ['image_profile'=>$image_profile]) ?>
      <?php View::partial("looper/aside", params: []) ?>

      <main class="app-main">
        <div class="wrapper">
          <?= View::content() ?>
        </div>
      </main>
      <footer class="app-footer">
        <?php View::partial("looper/footer", params: []) ?>
      </footer>
    </div>
  </body>

</html>