<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
</div>

<div class="w3-row">
  
  <div class="w3-half w3-container">
  <?php
    $tot_regs = count($data);
    if ($tot_regs==0) {
        Flash::valid('<h3>Atención!</h3><p>No hay registros para mostrar.</p>');
    } else {
        echo OdaForm::inputSearch();
        $tabla = new OdaTable();
        $tabla->setHead( arr_head: '°Salon, °Asignatura, °Profesor' );
        $tabla->setCaption(caption:'Carga Total Asignada');
        foreach($data as $key => $carga) {
          $d1 = "[$carga->user_id] ".OdaUtils::sanearString($carga->profesor);
          $d2 = "[$carga->asignatura_id] ".OdaUtils::sanearString($carga->asignatura);
          $d3 = "[$carga->salon_id] $carga->salon";
          $tabla->setBody( data: [$d1, $d2, $d3], attrs2:['class="searchTdata"','class="searchTdata"','class="searchTdata"']);
        }
        echo $tabla;
    }
  ?>
  </div>

  <div class="w3-half w3-container">
    <h2>Agregar Carga</h2>
    
    <div id="result">
      <?= OdaForm::number('profe_sel', '', 1) ?>
      <div id="asignatura_sel"></div>
      <div id="salon_sel"></div>
    </div>

    <button id="btn_materia" onclick="traer_materias()">Elegir Materia</button>

    <div id="materias">
      <div id=result_materias></div>
      <div id="salones">
        <div id=result_salones></div>
      </div>
    </div>
  </div>

</div>


<?= Tag::js("table_filter"); ?>


<script>
  document.addEventListener('DOMContentLoaded', function () {
    console.clear();
    //document.getElementById('result').style.display="none";
    document.getElementById('materias').style.display="none";
    document.getElementById('salones').style.display="none";

  });

  function traer_materias() {
    //console.clear();
    w3.hide('#btn_materia');
    w3.show('#materias');

    let ruta = document.getElementById('public_path').innerHTML.trim()+'api/asignaturas/all';
    let plantilla = "<ul class=\"w3-ul w3-border\"> <li><h2>Materias</h2> </li>ITEMS</div>";
    let output = '';
    
    fetch(ruta)
      .then((res) => res.json())
      
      .then(datos => {
          console.log(datos);
          for (let materia in datos) {  
            output = output + "<li> <button id=\""+datos[materia].id+"\" class=\"w3-btn w3-blue\" onclick=\"traer_salones("+datos[materia].id+")\">"+datos[materia].nombre+"</button> </li>";
          }
          plantilla = plantilla.replace('ITEMS', output);
          document.querySelector('#result_materias').innerHTML = plantilla;
      })
      .catch(
          error => console.log(error)
    );
  }

  
  function traer_salones(asignatura_sel) {
    w3.hide('#result_materias');
    w3.show('#salones');
    document.getElementById('asignatura_sel').innerHTML = asignatura_sel;

    let ruta = document.getElementById('public_path').innerHTML.trim()+'api/salones/all';
    let plantilla = "<ul class=\"w3-ul w3-border\"> <li><h2>Salones</h2> </li>ITEMS</div>";
    let output = '';
    fetch(ruta)
      .then((res) => res.json())
      .then(datos => {
          console.log(datos);
          for (let salon in datos) {  
            output = output + "<li> <button id=\""+datos[salon].id+"\" class=\"w3-btn w3-blue\" onclick=\"asignar_carga("+datos[salon].id+")\">"+datos[salon].nombre+"</button> </li>";
          }
          plantilla = plantilla.replace('ITEMS', output);
          document.querySelector('#result_salones').innerHTML = plantilla;
      })
      .catch(
          error => console.log(error)
    );
  }



  function asignar_carga(salon_sel) {
    asignatura_sel = document.getElementById('asignatura_sel').innerHTML.trim();
    profe = document.getElementById('profe_sel').value;
    let ruta = document.getElementById('public_path').innerHTML.trim()+'api/carga/asignar_carga/'+salon_sel+'/'+asignatura_sel+'/'+profe; 

    fetch(ruta)
      .then((res) => res.json())
      .then(datos => {
        location.reload()
      })
      .catch(
          error => console.log(error)
    );


  }


</script>
