<div class="w3-container"> 
  <?= View::flash().View::Encab($controller_name, $page_action, $breadcrumb) ?> 
</div>

<?php 
// PENDIENTE PROGRAMAR ::
// Estadísticas de avance de la digitación de notas 
?>

<div class="w3-row">
  
  <div class="w3-container w3-twothird">
    <?php
      echo OdaForm::inputSearch();
      $tabla = new OdaTable(showTotalRegs: true);
      $tabla->setHead("*Asignatura, *Salon, Indicadores, Notas", 
        arr_attrs_th: ['style="width:40%;"', 'style="width:30%;"', 'style="width:15%;"', 'style="width:15%;"'] );
      $tabla->setCaption(caption:'Carga Asignada');

      foreach($data as $key => $carga) {
        $d1 = OdaUtils::sanearString($carga->asignatura).' '.(($user_id==1)?"[$carga->asignatura_id]":'');
        $d1 .= (($user_id==1) ? "<br> [$carga->profesor]" :'');
        $d2 = $carga->salon . ' ' .(($user_id==1) ? "[$carga->salon_id]" :'');
        $d3 = OdaTags::link("docentes/listIndicadores/$carga->grado_id/$carga->asignatura_id", 'Indicadores');
        $d4 = OdaTags::link("docentes/listNotas/$carga->asignatura_id/$carga->salon_id", 'Notas');
        $tabla->addRow( data: [$d1, $d2, $d3, $d4], attrs_td:['class="searchTdata"','class="searchTdata"']);
      }
      echo $tabla;
      echo Tag::js("table_filter");
    ?>
  </div>

  <div class="w3-container w3-rest">
    <?php 
    try {
      OdaLog::debug("mensaje","rastreo");
      $periodo = Config::get('config.academic.periodo_actual');
      $user = Session::get('id');
      echo OdaTags::linkExterno(
        url: "https://windsortemp.schoolnext.space/index.php/+/sAP/ListasClaseProfesorPDF?user_id=$user", 
        text: "Listas de Clase P$periodo",
        attrs: 'class="w3-button w3-green"' );
    
    } catch (\Throwable $th) {
      OdaFlash::error($th);
    }
    ?>
  </div>

</div>