<div class="w3-container"> 
  <?= View::flash().View::Encab($controller_name, $page_action, $breadcrumb) ?> 
</div>
<?php 

?>
<div class="w3-row">
  <div class="w3-container w3-twothird">
    <?php
    $tot_regs = count($data);
    if ($tot_regs==0) {
      Flash::valid('<h3>Atención!</h3><p>No hay registros para mostrar.</p>');
    } else {
      echo OdaForm::inputSearch();
      $tabla = new OdaTable(showTotalRegs: true);
      $tabla->setHead("*Asignatura, *Salon, Indicadores, Notas", 
        arr_attrs_th: ['style="width:40%;"', 'style="width:30%;"', 'style="width:15%;"', 'style="width:15%;"'] );
      $tabla->setCaption(caption:'Carga Asignada');

      foreach($data as $key => $carga) {
        $d1 = OdaUtils::sanearString($carga->asignatura).' '.(($user_id==1)?"[$carga->asignatura_id]":'');
        $d1 .= (($user_id==1) ? "<br> [$carga->profesor]" :'');

        $d2 = $carga->salon . ' ' .(($user_id==1) ? "[$carga->salon_id]" :'');
        
        $d3 = OdaTags::link("docentes/listIndicadores/$carga->grado_id/$carga->asignatura_id", 'Indicadores');
        $d4 = OdaTags::link("docentes/listNotas/$carga->asignatura_id/$carga->salon_id", 'Notas');
        $tabla->addRow( data: [$d1, $d2, $d3, $d4], attrs_td:['class="searchTdata"','class="searchTdata"']);
      }
      echo $tabla;
      echo Tag::js("table_filter");
    }
    ?>
  </div>
  <div class="w3-container w3-rest">
    <?php 
      echo OdaTags::linkExterno(
        url: "https://windsortemp.schoolnext.space/index.php/+/sAP/ListasClaseProfesorPDF?user_id=22800", 
        text: 'Listas de Clase P1',
        attrs: 'class="w3-button w3-green"' );
    ?>
  </div>

</div>

