<div class="w3-container"> 
  <?= View::flash().View::Encab($controller_name, $page_action, $breadcrumb) ?> 
</div>

<?php 
// PENDIENTE PROGRAMAR ::
// Estadísticas de avance de la digitación de notas 
?>

<div class="w3-row">
  
  <div class="w3-container w3-twothird">
    <?php
      try {
        echo OdaForm::inputSearch();
        $tabla = new OdaTable(showTotalRegs: true);
        $tabla->setHead("*Asignatura, *Salon, Estudiantes, Indicadores, Notas", 
          arr_attrs_th: ['style="width:40%;"', 'style="width:30%;"', 'style="width:15%;"', 'style="width:15%;"'] );
        $tabla->setCaption(caption:'Carga Asignada');

        foreach($data as $key => $carga) {
          $tabla->addRow( 
            data: [
              $carga->getAsignaturaF($user_id, $carga->asignatura_nombre, $carga->profesor_nombre),
              $carga->getSalonF($user_id, $carga->salon_nombre), 
              $carga->tot_estudiantes, 
              $carga->getLnkPageIndicadores($carga->grado_id),
              $carga->getLnkPageListNotas(),
            ], 
            attrs_td: [
              'class="searchTdata"',
              'class="searchTdata"'
            ]
          );
        }
        echo $tabla;
        echo Tag::js("table_filter");
      
      } catch (\Throwable $th) {
        OdaFlash::error($th);
      }
    ?>
  </div>

  <div class="w3-container w3-rest">
    <?php 
    try {
      $periodo = Config::get('config.academic.periodo_actual');
      $user = Session::get('id');
      $lnk5p = '';
      if (4 == $periodo) {  
        // esta parte se debe quitar
        // $lnk5p = SalAsigProf::getLnkListaClase(5);

        $lnk5p = OdaTags::linkExterno(
          url: "https://windsortemp.schoolnext.space/index.php/+/sAP/ListasClaseProfesorPDF?user_id=$user&periodo=5", 
          text: "Listas de Clase P5",
          attrs: 'class="w3-button w3-green"' );

      }

      echo OdaTags::linkExterno(
        url: "https://windsortemp.schoolnext.space/index.php/+/sAP/ListasClaseProfesorPDF?user_id=$user", 
        text: "Listas de Clase P$periodo",
        attrs: 'class="w3-button w3-green"' )
        .'<br>'.$lnk5p;
    
      
    } catch (\Throwable $th) {
      OdaFlash::error($th);
    }
    ?>
  </div>

</div>