<?php
  
  $tabla = new OdaTable();
  $tabla->setCaption('DESCARGAR DOCUMENTOS DE MATRÍCULA',
        attrs: 'class="w3-center-align w3-bottombar w3-border-blue"');

  $instrucciones = OdaTags::tag('h3', 'Instrucciones:<br>') 
  .OdaTags::list([
    'Descargar estos documentos', 
    'Diligenciarlos según las instrucciones.', 
    'Escanearlos en formato PDF o IMAGEN, cada uno por aparte', 
    'Subirlos de manera independiente',
  ], 'ol', attrs: 'class="w3-ol w3-card-4"');
  
  $widgetLinkFikle1 = OdaTags::linkExterno(Config::get('matriculas.file_1'), 'Descargar '.Config::get('matriculas.file_1_titulo'), 'class="w3-button w3-ripple w3-block"');
  $widgetLinkFikle2 = OdaTags::linkExterno(Config::get('matriculas.file_2'), 'Descargar '.Config::get('matriculas.file_2_titulo'), 'class="w3-button w3-block"');
  $widgetLinkFikle3 = OdaTags::linkExterno(Config::get('matriculas.file_3'), 'Descargar '.Config::get('matriculas.file_3_titulo'), 'class="w3-button w3-ripple w3-block"');
  $widgetLinkFikle4 = OdaTags::linkExterno(Config::get('matriculas.file_4'), 'Descargar '.Config::get('matriculas.file_4_titulo'), 'class="w3-button w3-ripple w3-block"');
  $widgetLinkFikle5 = OdaTags::linkExterno(Config::get('matriculas.file_5'), 'Descargar '.Config::get('matriculas.file_5_titulo'), 'class="w3-button w3-ripple w3-block"');
  $widgetLinkFikle6 = OdaTags::linkExterno(Config::get('matriculas.file_6'), 'Descargar '.Config::get('matriculas.file_6_titulo'), 'class="w3-button w3-ripple w3-block"');

  $tabla->addRow([$widgetLinkFikle1]);
  $tabla->addRow([$widgetLinkFikle2]);
  $tabla->addRow([$widgetLinkFikle3]);
  $tabla->addRow([$widgetLinkFikle4]);
  $tabla->addRow([$widgetLinkFikle5]);
  $tabla->addRow([$widgetLinkFikle6]);

  $btn_subir_arch = OdaTags::linkButton("padres/subirArchivos/$estud->id", 'Subir Archivos');

  $contenido_tab .= "
  <div class=\"w3-panel w3-pale-red w3-leftbar w3-border-red\">
    <p>Estado del proceso [{$estado_mat->value}]: <b>{$estado_mat->label()}</b></p>
    <p>{$estado_mat->comments()}</p>
  </div>
    $instrucciones
    $tabla
  <br><br>
  <div class=\"w3-display-container\">
    $btn_subir_arch
  </div>
  ";
?>