<div class="w3-container">
  <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
  <?php View::flash(); ?>
</div>

<div class="w3-container">
  <?php
  $message = Config::get('messages.comprimir_imagenes');
  $model = $arrData['Adjuntos'];
  $fieldsToHidden = $model::getFieldsHidden('edit');
  
  $myForm = new OdaForm(
    $model, "admin/estudiante_adjuntos/edit_ajax/$model->id/padres.matriculas", 
    multipart: true,
    url_back: 'padres/matriculas',
  );
  $myForm->setEdit();
  $myForm->setColumnas(2);
  $myForm->setAtrib('id="frm_edit" name="frm_edit"');

  
  $num_archivos = (int)Config::get('matriculas.'.INSTITUTION_KEY.'.num_archivos');
  for ($i=1; $i<=$num_archivos; $i++) { 
    $myForm->addFile2('nombre_archivo'.$i);
  }
  $myForm->addHiddens(implode(",", $fieldsToHidden));
  echo OdaTags::tag('div', $message, 'class="w3-panel"');
  echo "<div class=\"w3-container\">$myForm</div>";
  ?>

  <pre>
    <?php
      if (1==$user_id && 1==Config::get('config.application.modo_depuracion_admin')) {
        echo "<p>Campos Incluidos</p>";
        print_r( $myForm->getFieldsInForm() );
        echo "<p>Campos que faltan</p>";
        print_r( $myForm->getFieldsNotInForm() );
        echo "<p>Campos Ocultos</p>";
        print_r($fieldsToHidden);
      }
    ?>
  </pre>

</div>