<div class="w3-panel">
  <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
  <?= View::flash(); ?>
  <?= View::partial("snippets/ejemplo_cards") ?>
  <?= View::partial(partial: 'eventos_dashboard', params: ['data'=>$data]); ?>

  <hr>
  <?=OdaTags::linkExterno('https://github.com/KumbiaPHP/Documentation/tree/master/es', 'Kumbia PHP Doc', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://developer.mozilla.org/es/docs/Web/HTML', 'MDN Html', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://developer.mozilla.org/eS/docs/Web/JavaScript', 'MDN Javascript', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/w3css/default.asp', 'w3-CSS', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/w3js/default.asp', 'w3-JS', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/js/default.asp', 'w3-Javascript', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/howto/default.asp', 'w3 HowTO ?', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://respect-validation.readthedocs.io/en/latest/', 'Respcet Validation', 'class="w3-button w3-bar-item w3-hover-blue"' );?>
  <?=OdaTags::linkExterno('https://php.watch/versions/8.0', 'Novedades PHP 8.0', 'class="w3-button w3-bar-item w3-hover-blue"' );?>

  <hr>
  <?= OdaTags::linkBarItem('pages/tools/odautils', 'Utilidades', 'class="w3-button"') ?>
  <?= OdaTags::linkBarItem('pages/tools/colores', 'Colores W3', 'class="w3-button"') ?>
  <?= OdaTags::linkBarItem('pages/tools/iconos', 'Íconos FA', 'class="w3-button"') ?>

  <hr>
  <?= OdaTags::linkBarItem('pages/ejemplos/archivos', 'Archivos', '') ?>
  <?= OdaTags::linkBarItem('pages/ejemplos/validar.backend', 'Validar Backend', '') ?>
  <?= OdaTags::linkBarItem('pages/ejemplos/datalists', 'Data Lists', '') ?>
  <?= OdaTags::linkBarItem('pages/ejemplos/excel', 'Excel', '') ?>
  <?= OdaTags::linkBarItem('pages/ejemplos/pdf', 'PDF', '') ?>
  <?= OdaTags::linkBarItem('pages/ejemplos/tabs', 'Tabs', '') ?>
  <?= OdaTags::linkBarItem('pages/ejemplos/js_validations', 'Validaciones Forms', '') ?>
</div>