<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
</div>

<div class="w3-container w3-row">
   
   <div class="w3-threequarter">
      <?php if($tot_regs==0): ?>
         <?= Flash::valid('<h3>Atención!</h3><p>No hay registros para mostrar.</p>');?>
         <?php else: ?>
            <?= OdaForm::inputSerach();?>
            <span class="w3-small"><?= 'Total Registros: '.count($data); ?></span><br/>   
            <table id="myTable" class="w3-table w3-border w3-responsive w3-hoverable">
               <thead>
                  <tr class="w3-theme-<?=$themei?>3">
                     <?=_Tag::multiTags('th', array('ID', 'Periodo', 'Fecha', 'Estudiante', 'Asunto')); ?>
                  </tr>
               </thead>
               
            <tbody>      
               <?php foreach($data as $key => $reg) : ?>
                  <tr class="item w3-theme-<?=((($key%2)==0)?$themei.'1':$themei.'2');?> ">
                     <td><?=$reg->id?></td>
                     <td><?=$reg->annio?>-<?=$reg->periodo_id?></td>
                     <td><?=$reg->getFecha('d M')?></td>
                     <td class="searchTdata"><?=ucwords(OdaUtils::sanear_string($reg->estudiante)); ?> </td>
                     <td>
                        <?=substr($reg->asunto, 0, 120)?>... 
                        <button onclick="document.getElementById('<?=$reg->id?>').style.display='block'" class="w3-btn w3-theme-d5">ver mas</button>
                     </td>
                  </tr>
                  <?php require '_modal.phtml'; ?>
                  <?php endforeach ?>
               </tbody>
            </table>
            <?php endif; ?>
   </div>
         
         
   <div class="w3-rest">
      <?= require '_resumen.phtml'; ?>
   </div>

</div>
      

<?=Tag::js("table_filter", false);?>