<div class="w3-container w3-padding w3-center">
  <?= View::flash(); ?>
  <br>

  <div class="w3-display-container w3-padding w3-center">
      
    <div class="w3-display-topmiddle w3-row">
      
        <div class="w3-padding w3-row w3-blue-gray">
          <br>
          <?= _Tag::img('ws_logo.png', 'logo', "style=\"width:80%;\""); ?>
        </div> 

        <div class="w3-padding w3-row w3-blue-gray">
            <h2>SchoolNext App</h2>
            <h3>Acceso Web</h3>
        </div>
          
        <div class="w3-padding w3-row w3-blue-gray">
              <?php echo Form::open('auth/login','post','class="w3-center"') ?>
                <input name="mode" type="hidden" value="auth">
                <?= Form::text('username', 'class="w3-center w3-input w3-border w3-hover-pale-yellow" placeholder="Ingrese USUARIO"') ?><br>
                <?= Form::password('password', 'class="w3-center w3-input w3-border w3-hover-pale-yellow" placeholder="Ingrese CLAVE"  ') ?>
                <p><?= Form::submit('ENTRAR') ?></p>
                <?php echo Form::close(); ?>
        </div>
            
        <div class="w3-padding w3-row">
              <br/><b>¿Necesita ayuda para ingresar?</b><br/>
              <a title="Escríbenos" href="whatsapp://send?phone=<?=$soporte_telefono?>&amp;text=Requiero+soporte+técnico">
                <?= _Icons::brands('whatsapp', 'w3-xxlarge')?> </a>
                
                <a title="Llámanos" href="tel:<?=$soporte_whatsapp?>">
                  <?= _Icons::solid('square-phone', 'w3-xxlarge')?> </a>
                  
                  <a title="Envianos un email" href="mailto:<?=$soporte_email?>">
                    <?= _Icons::solid('envelope', 'w3-xxlarge')?></a>
                    <br/>
                    <span>
                      <?= $copy_right ?><br/>
                      <?= $copy_text ?><br/>
                      <a href="<?=$sw_house_twitter?>" target="_blank"><?=$sw_house_name?></a> 
                    </span>
        </div>
    </div>


  </div>

</div>


<script>
  window.onload = function() {
    document.getElementById("username").focus();
  };
</script>