<?php View::content() ?>

<div class="w3-container">
  <?php echo _Tag::linkButton('admin/grados/list','Volver a la Lista') ?>  
  <h1>Crear Grado</h1>
  <div class="w3-row">
    <?php
          $Modelo = new Grado();
          $myForm = new OdaForm($Modelo::class, 'admin/grados/create', 1);
          //$myForm->_isNew = true;

          $myForm->addInput(1, 'text',   'nombre');
          
          $myForm->addInput(1, 'text',   'abrev');
          $myForm->addInput(1, 'number', 'salon_default');
          $myForm->addInput(1, 'number', 'valor_matricula');
          $myForm->addInput(1, 'number', 'valor_pension');
          $myForm->addSelect(1, 'seccion_id', $Modelo::SECCIONES, 'required pattern="'.implode('|', $Modelo::SECCIONES).'"') ;

          $myForm->addInput(1, 'number', 'orden');
          $myForm->addInput(1, 'number', 'proximo_grado');
          $myForm->addInput(1, 'number', 'proximo_salon');

          $myForm->addHiddens('created_by,updated_by,created_at,updated_at');
          
          echo $myForm;
    ?>

  </div>
</div>
