<?php View::content() ?>

<div class="w3-container">
  <?php echo OdaTags::linkButton('admin/grados/list','Volver a la Lista') ?>
  
  <h1>Crear Grado</h1>
  <div class="w3-row">
    <?php
          $myForm = new OdaForm(new Grado(), 'admin/grados/create');
          $myForm->setColumnas(2);
          $myForm->setAtrib('id="form_new"');

          $myForm->addInput(1,  'text',   'nombre');
          $myForm->addInput(1,  'text',   'abrev');
          $myForm->addSelect(1, 'salon_default', $salones, 'required pattern="'.implode('|', $salones).'"') ;
          $myForm->addInput(1,  'number', 'valor_matricula');
          $myForm->addInput(1,  'number', 'valor_pension');
          $myForm->addSelect(1, 'seccion_id', $secciones, 'required pattern="'.implode('|', $secciones).'"') ;

          $myForm->addInput(2,  'number', 'orden');
          $myForm->addSelect(2, 'proximo_grado', $grados, 'required pattern="'.implode('|', $grados).'"') ;
          $myForm->addSelect(2, 'proximo_salon', $salones, 'required pattern="'.implode('|', $salones).'"') ;

          $myForm->addHiddens('is_active,created_by,updated_by,created_at,updated_at');

          echo $myForm;
    ?>

  </div>
</div>
