<?php View::content() ?>

<div class="w3-container">
  <?php echo _Tag::linkButton('admin/grados/list','Volver a la Lista') ?>
  <h1>Crear Grado</h1>
  
  <div class="w3-panel">
    <?php
          $Modelo = new Grado();
          $myForm = new _Form($Modelo::class, 'admin/grados/create', 2);
          $myForm->_isNew = true;

          $myForm->addInput(1, 'text',   'nombre');
          $myForm->addInput(1, 'text',   'abrev');
          $myForm->addInput(2, 'number', 'salon_default');
          $myForm->addInput(1, 'number', 'valor_matricula');
          $myForm->addInput(1, 'number', 'valor_pension');
          $myForm->addSelect(1, 'seccion_id', $Modelo::SECCIONES, 'required pattern="'.implode('|', $Modelo::SECCIONES).'"') ;

          $myForm->addInput(2, 'number', 'orden');
          $myForm->addInput(2, 'number', 'proximo_grado');
          $myForm->addInput(2, 'number', 'proximo_salon');

          echo $myForm;
    ?>

  </div>
</div>
