<?php View::content() ?>

<div class="w3-container">
  <?php echo _Tag::linkButton('admin/grados/list','Volver a la Lista') ?>
  
  <h1>Edit Grado </h1>
    <?php
        $myForm = new OdaForm($Modelo, 'admin/grados/edit');
        $myForm->setEdit();
        $myForm->setColumnas(2);
        $myForm->setAtrib('id="form_edit"');
        
        $myForm->addInput(1,  'text', 'nombre');
        $myForm->addInput(1,  'text', 'abrev');
        $myForm->addSelect(1, 'salon_default', $salones, 'required pattern="'.implode('|', $salones).'"') ;
        $myForm->addInput(1,  'number', 'valor_matricula');
        $myForm->addInput(1,  'number', 'valor_pension');
        $myForm->addSelect(1, 'seccion_id', $secciones, 'required pattern="'.implode('|', $secciones).'"') ;
        
        $myForm->addInput(2,  'number', 'orden');
        $myForm->addSelect(2, 'proximo_grado', $grados, 'required pattern="'.implode('|', $grados).'"') ;
        $myForm->addSelect(2, 'proximo_salon', $salones, 'required pattern="'.implode('|', $salones).'"') ;
        //$myForm->addInput(2,  'number', 'is_active');
        $myForm->addRadio(2, 'is_active');
        $myForm->addHiddens('id,uuid,created_by,created_at,updated_by,updated_at');
        echo $myForm;
    ?>

</div>