<div class="w3-panel">
  <?php 
  $tot_regs = count($data);
  require('listHeader.phtml');

  $tabla = new OdaTable();
  $tabla->setHead(array('Acciones', 'Grado', 'Id', 'Estado', 'Abrev', 'Sección', 'Matr&iacute;cula', 'Pensi&oacute;n'));
  foreach ($data as $key => $grado) {
    $lnkEditar = OdaTags::linkIcon("admin/grados/edit/$grado->id/", 'square-pen', 'title="Editar Registro"' );
    $lnkBorrar = Js::link("admin/grados/del/$grado->uuid", _Icons::solid('trash-can'), "Atención: ¿Quiere eliminar: Grado $grado->nombre?", 'title="Eliminar Registro"');
    $arrBody = array( 
      $lnkEditar.'&nbsp;&nbsp;'.$lnkBorrar, 
      $grado->nombre, 
      $grado->id, 
      $grado->getIsActiveF(true), 
      $grado->abrev, 
      $grado->seccion, 
      $grado->valor_moneda($grado->valor_matricula), 
      $grado->valor_moneda($grado->valor_pension),
      );
    $tabla->setBody($arrBody);
  }
  echo $tabla;
  
  require('listFooter.phtml');

  ?>
</div>
<?php Tag::js('jquery/jquery+kumbiaphp.min', false);?>