<?php
  $model = new Indicador;
  $myForm = new OdaForm($model, 'admin/indicadores/create_ajax');
          $myForm->setAtrib('id="form_new"');
          $myForm->addInput(columna:1, tipo:'number', field:'codigo', attr:'required min:100 max 399');
          $myForm->addInput(columna:1, tipo:'text', field:'concepto', attr:'required');
          $myForm->addSelect(columna:1, field:'valorativo', data: $model::$valorativos);
          $myForm->addHiddens('annio, periodo_id, grado_id, asignatura_id, is_active, is_visible, created_by, updated_by, created_at, updated_at');
  return "<div class=\"w3-container\" id=\"formulario\" style=\"display: none;\">$myForm</div>";
?>
