<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
</div>

<div class="w3-container w3-row">   
   <div class="w3-threequarter">
      <?php
         if ($tot_regs==0) {
            Flash::valid('<h3>Atención!</h3><p>No hay registros para mostrar.</p>');
         } else {
            require('listHeader.phtml');
            $tabla = new OdaTable();
            $tabla->setHead('ID, Periodo, Fecha, Estudiante, Asunto');
            foreach($data as $key => $reg) {
               $data_row = array(
                  $reg->id,
                  $reg->annio .'-' .$reg->periodo_id,
                  $reg->getFecha('d M'),
                  ucwords(OdaUtils::sanearString($reg->estudiante)),
                  OdaUtils::truncate($reg->asunto, 120)
                    ."<button onclick=\"document.getElementById('$reg->id').style.display='block'\" class=\"w3-btn w3-theme\">ver mas</button>",
                  );
               require 'list_modal.phtml';
               $tabla->setBody(data: $data_row, attrs2:['','','','class="searchTdata"']);
            } //END-FOR
            echo $tabla;
            require('listFooter.phtml');
         }//END-IF
      ?>
   </div>
   <div class="w3-rest"><?= require 'list_resumen.phtml'; ?></div>
</div>
      
<?=Tag::js("table_filter", false);?>