<div class="w3-panel">
<?php

  try {
    $ModeloAspirante  = new Aspirante();
    $FormAspir = new OdaForm(modelo: $ModeloAspirante, action: 'admin/aspirantes/crear');

    $ModeloAspirPsico  = new AspirantePsico();
    $FormAspirPsico = new OdaForm(modelo: $ModeloAspirPsico, action: '');

    $privacidad    = require('form_info_privacidad.phtml');
    $datos_basicos = require('form_info_basicos.phtml');
    $datos_padre   = require('form_info_padre.phtml');
    $datos_madre   = require('form_info_madre.phtml');
    $hist_pers     = require('form_info_hist_pers.phtml');
    $desa_psico   = require('form_info_desa_psico.phtml');

    $antec_fami   = require('form_info_antec_fami.phtml');
    $hist_escolar   = require('form_info_hist_escolar.phtml');
    $academico   = require('form_info_academico.phtml');
    $documentos   = require('form_info_doc_adjuntos.phtml');
    $final   = require('form_info_final.phtml');
    
    $tabs = new OdaTabs();
    
    $tabs->addTab('privacidad', 'Privacidad', $privacidad, true);
    $tabs->addTab('documentos','Documentos', $documentos, true);
    $tabs->addTab('basicos', 'Básicos', $datos_basicos, true);
    $tabs->addTab('madre', 'Madre', $datos_madre, true);
    $tabs->addTab('padre', 'Padre', $datos_padre, true);
    $tabs->addTab('hist_pers', 'Personal', $hist_pers, true);
    $tabs->addTab('desa_psico','Desa Psico', $desa_psico, true);
    $tabs->addTab('antec_fami','Familia', $antec_fami, true);
    $tabs->addTab('hist_escolar','Escolar', $hist_escolar, true);
    $tabs->addTab('academico','Academico', $academico, true);
    $tabs->addTab('final','Final', $final, true);

    echo  $FormAspir->getOpenForm()
          .$tabs
          .$FormAspir->getCloseForm();
  
  } catch (\Throwable $th) {
    OdaFlash::error($th);
  }
  
?>
</div>
