<?php 
try {  
  $tabla = new OdaTable('id="myTable-m" class="w3-table w3-responsive w3-striped w3-bordered" style="width:100%"');
  //$tabla->setCaption('Resultados de Examenes');

  
  $tabla->addRow(
    data: [
      $FormAspir->getLabel('estatus').$ModeloAspirante->estatus_f(), 
      '',
      $FormAspir->getCheck('is_pago'), 
    ],
  );
  
  $tabla->addRow(
    data: [
      $FormAspir->getDataLabel('is_active').' '.$ModeloAspirante->is_active_f(),
      '', 
      $FormAspir->getLabel('ctrl_llamadas').
        AspirLlamadas::forSelect('aspirantes_ctrl_llamadas', 'aspirantes[ctrl_llamadas]', $ModeloAspirante->ctrl_llamadas),
    ],
  );
  
    
  $tabla->addRow(
    data: [
      $FormAspir->getDataLabel('fecha_entrev'), 
      '', 
      $FormAspir->getDataLabel('fecha_eval'), 
    ],
  );
  
  $tabla->addRow(
    data: [
      '',
      $FormAspir->getSubmitForm('Guardar'),
      '',
    ],
  );
  
  return $FormAspir->getInput(field: 'id', tipo: 'hidden') . $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}