<?php 
try {  
  $tabla = new OdaTable('id="myTable-m" class="w3-table w3-responsive w3-striped w3-bordered" style="width:100%"');
  
  $select_grado = (new Grado)::getSelectGrados('aspirantes_grado_aspira', 'aspirantes[grado_aspira]', $ModeloAspirante->grado_aspira);
  $tabla->addRow(
    data: [
      $FormAspir->getDataLabel('fecha_insc'), 
      '',
      $FormAspir->getLabel('grado_aspira').$select_grado, 
    ],
  );
  

  $tabla->addRow(
    data: [
      $FormAspir->getCheck('is_pago'), 
      '',
      $FormAspir->getLabel('estatus').$ModeloAspirante->estatus_f(), 
    ],
  );
  
  $tabla->addRow(
    data: [
      $FormAspir->getLabel('ctrl_llamadas').
      AspirLlamadas::forSelect('aspirantes_ctrl_llamadas', 'aspirantes[ctrl_llamadas]', $ModeloAspirante->ctrl_llamadas),
      '',
      '', 
    ],
  );
  
    
  $tabla->addRow(
    data: [
      $FormAspir->getDataLabel('fecha_entrev'), 
      '', 
      $FormAspir->getDataLabel('fecha_eval'), 
    ],
  );
  
  $tabla->addRow(
    data: [
      '',
      $FormAspir->getSubmitForm('Guardar'),
      '',
    ],
  );
  
  return $FormAspir->getInput(field: 'id', tipo: 'hidden')
        .$tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}