<div class="w3-panel">
    <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
    <?= View::flash(); ?>
</div>

<div class="w3-panel">
    <div  class="w3-bar">
        <?php 
        foreach ($annios as $key => $annio) {
            echo "<div  id=\"btn-$key\"  onclick=\"traer_data($annio)\" class=\"w3-button w3-bar-item\">$annio</div>" ;
        }
        ?>
    </div>

    <div id="salon"></div>
    <div id="resultados"></div>
</div>

<?= tag::js("registros/observaciones_generales", false) ?>