<div class="w3-panel">
    <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
    <?= View::flash(); ?>
</div>

<div class="w3-panel">
    <div  class="w3-bar">
      hola
        <?php 
        foreach ($data as $key => $annio) {
            echo "<div  id=\"btn-$key\"  onclick=\"traer_salones($user_id, $annio)\" class=\"w3-button w3-bar-item\">$annio</div>" ;
        }
        ?>
    </div>

    <div id="salones" class="w3-panel"></div>
    <div id="botones" class="w3-panel"></div>
    <div id="resultados" class="w3-panel"></div>
</div>

<?= tag::js("coordinador/registros/dg_registros_consolidados", false) ?>