<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
</div>



<div class="w3-row">
  
  <div class="w3-container w3-half">
    <h2>Corregir Registros Huerfanos</h2>
    <?= OdaTags::linkButton('admin/correcciones/corregirRegistrosHuerfanos', 'Corregir Registros Huerfanos') ?>
  </div>
  
  <div class="w3-container w3-half">
  </div>

</div>