<?php

echo 
'
<div style="text-align: justify;">
  <div style="text-align: center;">
    <span lang="ES" style="font-size: 10pt; font-family: Arial; font-weight: bold;">REPÚBLICA DE COLOMBIA</span>
    <br/>
    <span lang="ES" style="font-size: 10pt; font-family: Arial; font-weight: bold;">VALLEDUPAR-CESAR</span>
    <br/><br/>
    <span lang="ES" style="font-size: 10pt; font-family: Arial; font-weight: bold;">CONTRATO DE PRESTACION DE SERVICIOS EDUCATIVOS No. <u>$CONTRATO$</u></span>
    <br/>
    <span lang="ES" style="font-size: 10pt; font-family: Arial; font-weight: bold;">PREESCOLAR <u>$PRES$</u> BASICA PRIMARIA <u>$BPRIM$</u> BASICA SECUNDARIA <u>$BSEC$</u> MEDIA ACADÉMICA <u>$MEDA$</u></span>
  </div>
  <br/>
  <span lang="ES" style="font-size: 10pt; font-family: Arial;">
    Entre los suscritos a saber, de una parte <strong><u>$REPRESENTANTE$</u></strong> mayor de edad, 
    identificado como aparece al pie de su firma, en nombre y representación del Colegio WINDSOR, 
    quien en adelante se llamará <strong>EL COLEGIO</strong> y de la otra parte <strong><u>$ACUDIENTES$</u></strong> 
    en su condición de padres (o acudientes) del <strong>EDUCANDO</strong> <strong><u>$NOMBRE_ESTUDIANTE$</u></strong>,
    quienes en adelante se denominarán los PADRES (o Acudientes); en cumplimiento de los artículos 27, 67,68, y 70 
    de la Constitución Política y de la ley 115 de 1994 y para asegurar el derecho a la educación del <strong>EDUCANDO </strong>
    hemos celebrado el presente contrato que se regirá por las siguientes clausulas: 
    
    <strong>PRIMERA</strong>.
    <strong>DEFINICIÓN DEL CONTRATO: </strong>La naturaleza jurídica del presente contrato es de carácter civil 
    según lo estipulado en los arts. 95 y 2001 de la ley 115 de 1994, mediante la cual se formaliza la vinculación del 
    <strong>EDUCANDO</strong> al servicio educativo que ofrece <strong>EL COLEGIO</strong> en los 
    términos del artículo 95 del la ley 115 de 1994, y se compromete a las partes y al <strong>EDUCANDO </strong>
    en las obligaciones legales y pedagógicas tendientes a ser efectivas la función social de la prestación del 
    servicio público educativo por parte de los colegios privados, obligaciones que son correlativas y esenciales 
    para la consecución del objeto y los fines comunes ya que el derecho a la educación se considera un derecho-deber; 
    de tal manera que al incumplimiento de las obligaciones adquiridas por las partes, hacen imposible la consecución del fin común.
    
    <strong>SEGUNDA. OBJETO DEL CONTRATO:</strong>
    El objeto del contrato es procurar la formación integral del <strong>EDUCANDO</strong>
    con la recíproca complementación de esfuerzos entre el <strong>EDUCANDO, LOS PADRES Y EL COLEGIO. </strong> 
    En la búsqueda del pleno desarrollo de la personalidad del <strong>EDUCANDO </strong> y de un rendimiento académico 
    satisfactorio en el ejercicio del programa curricular correspondiente al grado arriba señalado mediante el 
    Proyecto Educativo Institucional del <strong>COLEGIO, </strong> en el año lectivo <u>$ANNIO_LECTIVO$</u>.
    
    <strong>TERCERA. OBLIGACIONES DEL EDUCANDO:</strong> Son obligaciones del educando: 
    a) Asistir puntualmente al <strong>COLEGIO</strong>; 
    b) Cumplir las pautas y principios definidos y establecidos en el PEI y en el Reglamento Interno o Manual de Convivencia; 
    c) Respetar y valorar a todas las personas que constituyen la comunidad educativa; 
    d) Enaltecer con sus actuaciones y expresiones el buen nombre de <strong>COLEGIO; </strong>
    e) Asistir puntual y respetuosamente a todas y cada una de las actividades programadas por el <strong>COLEGIO; </strong>
    f) Asistir al <strong>COLEGIO</strong> portando los uniformes ( diario, educación física, otros) de acuerdo con el Manual de Convivencia; 
    g) Asistir obligatoriamente a las sesiones de preparación a las <strong>PRUEBAS SABER ICFES</strong> [grados: 3°, 5°, 7°, 9°, 10° y 11°], 
    en el horario señalado por el <strong>COLEGIO</strong> como también el pago oportuno del costo que dicho servicio requiere.
    
    <strong>CUARTA. OBLIGACIONES DE LOS PADRES:</strong>
    Son obligaciones de los <strong>PADRES</strong>: 
    a) pagar oportunamente el costo del servicio educativo (matricula, pensiones, otros cobros y cobros periódicos) 
    autorizados por el Consejo Directivo, dentro de las fechas establecidas para tal fin. Los pagos deben hacerse en las entidades 
    bancarias establecidas por el <strong>COLEGIO</strong>, utilizando la consignación y cuenta que determine <strong>EL COLEGIO</strong>. 
    Los pagos ordinarios de las obligaciones del presente contrato deberán hacerse dentro de los (5) primeros días calendario de cada mes. 
    A partir del día sexto de cada mes, toda mora o retardo en el cumplimiento de los pagos de las obligaciones económicas por parte de los 
    <strong>PADRES</strong> otorga al <strong>COLEGIO </strong>el derecho a liquidar y exigir los intereses moratorios equivalente al 
    máximo legal vigente, conforme a lo previsto en el art. 4 del Decreto 2642 de 1942 y demás normas aplicables al presente contrato, 
    según lo previsto en el art. 884 del C. Co y art. 191 del C.P.C.; 
    b) Pagar el veinte porciento (20%) en caso de devolución de un cheque como sanción conforme al art. 731 del C. Co; 
    c) Matricular al <strong>EDUCANDO </strong>en las fechas establecidas por <strong>EL COLEGIO</strong> cancelando los valores 
    correspondientes y presentando la documentación completa para su legalización; 
    d) Asumir la responsabilidad en todo tipo de tratamiento (psicológico, de lenguaje, etc.) que <strong>EL</strong> <strong>COLEGIO</strong> 
    considere que requiere el <strong>EDUCANDO</strong>, por dificultades en el aprendizaje y/o comportamiento, por tanto adquiere el 
    compromiso de buscar un profesional externo para efectuar el tratamiento correspondiente; 
    e) Asumir los gastos médicos, quirúrgicos, farmacéuticos, terapéuticos, etc, que sean ocasionados por el <strong>EDUCANDO </strong>
    a algún otro miembro de la comunidad educativa siempre que no estén contemplados en la cobertura del seguro escolar contra accidentes, 
    igualmente por daño en cosa ajena (instalaciones, lockers, pupitres, muebles, material didáctico, objetos personales, etc); 
    f) Comunicar por escrito con treinta (30) días de anticipación el retiro del <strong>EDUCANDO; </strong>
    g) Cancelar la emisión de nuevos recibos por concepto de pensiones y otros costos, en caso de pérdida o deterioro; 
    h) Cumplir estrictamente las citas y llamadas que hagan las Directivas del <strong>COLEGIO</strong> en desarrollo de las actividades 
    institucionales planeadas y aquellas ocasionales que ameriten citación; 
    i) Velar y participar activamente en el progreso del <strong>EDUCANDO </strong>en todos los órdenes; 
    j) Renovar la matricula del <strong>EDUCANDO</strong> para cada año académico, en los días y horas señalados para ellos; 
    k) Integrarse cumplida y solidariamente al <strong>COLEGIO </strong>para la formación del <strong>EDUCANDO; </strong>
    l) Abstenerse de hacer críticas destructivas que atenten contra el buen nombre del <strong>COLEGIO.</strong>
     
    <strong>QUINTA. OBLIGACIONES DEL COLEGIO: </strong>Son obligaciones del <strong>COLEGIO</strong>: 
    a) Impartir la enseñanza contratada y propiciar la mejor calidad y continuidad del servicio; 
    b) Prestar en forma regular el servicio educativo de acuerdo a las prescripciones legales, exigencias de las autoridades competentes y del PEI; 
    c) Desarrollar los planes y programas establecidos en el PEI; 
    d) Cumplir y exigir el cumplimiento del Reglamento Escolar o Manual de Convivencia, 
    e) Exigir el cumplimiento de los deberes académicos esenciales por parte del <strong>EDUCANDO </strong>para la obtención del fin común 
    que comparten con los <strong>PADRES. EL COLEGIO </strong> no se hace responsable del bajo rendimiento del <strong>EDUCANDO </strong> 
    cuando sea imputable a los <strong>PADRES </strong>o al propicio <strong>EDUCANDO.</strong>
    
    <strong>SEXTA. DERECHOS DE LOS PADRES</strong>: 
    Son derechos de los <strong>PADRES:</strong> 
    a) Exigir la regular prestación del servicio educativo; 
    b) Exigir el cumplimiento del PEI; 
    c) Participar en el proceso educativo, buscar y recibir orientación sobre la educación del <strong>EDUCANDO;</strong>
    d) Tener acceso al Manual de Convivencia o Reglamento Escolar en medio magnético para su descarga a través de la página web del <strong>COLEGIO</strong>; 
    e) Recibir información oportuna sobre los diferentes aspectos académicos, de comportamiento sociales, culturales y deportivos del <strong>EDUCANDO.</strong> 
      
    <strong>SÉPTIMA. DERECHOS DEL EDUCANDO: </strong>
    a) Recibir la educación integral acorde con los principios que inspiran el PEI; 
    b) A ser valorado y respetado como persona; 
    c) A participar activamente en el desarrollo del servicio educativo a través de los proyectos y programas establecidos por <strong>EL COLEGIO; </strong> 
    d) A recibir de los Directivos y Docentes buen ejemplo, acompañamiento, estímulo y atención y a ser escuchado oportunamente y a participar en 
    las instancias establecidas en el reglamento escolar. 
    
    <strong>OCTAVA. DERECHOS DEL COLEGIO: </strong>Son derechos del <strong>COLEGIO: </strong>
    a) Exigir el cumplimiento del Reglamento o Manual de Convivencia y todos los deberes allí contemplados; 
    b) exigir a los padres el cumplimiento de las obligaciones como responsables del <strong>EDUCANDO; </strong>
    c) recuperar los costos incurridos en el servicio educativo, exigir y lograr el pago de los derechos correspondientes a matricula, 
    pensión, otros cobros y cobros periódicos, por todos los medios lícitos a su alcance; 
    d) reservarse el derecho de NO-RENOVACIÓN DE MATRÍCULA según estipulaciones del reglamento escolar y por razones de comportamiento, 
    rendimiento o de capacidades que requieran tratamiento especial del <strong>EDUCANDO </strong>o incumplimiento reiterado de los deberes 
    y obligaciones por parte de los representantes (<strong>PADRES</strong>) del educando o trato irrespetuoso de este a directivos, profesores 
    y otros miembros de la institución<strong>; </strong>
    e) Obtener del Acudiente y/o representante del <strong>EDUCANDO, </strong>la garantía 
    y respaldo del pago de las obligaciones derivadas de este contrato, con firmas de pagarés, letras de cambio, etc. 
    
    <strong>NOVENA. COSTO DE CONTRATO: </strong>
    El presente contrato tiene un costo <strong>ANUAL DE <u>$COSTO_ANUAL_PALABRA$</u> PESOS (<u>$COSTO_ANUAL_NUMEROS$</u>)</strong>, los cuales serán cancelados 
    por los <strong>PADRES</strong> así: <strong>Matrícula <u>$VALOR_MATRICULA$</u></strong> y diez (10) cuotas de <strong><u>$VALOR_CUOTAS$</u></strong> 
    cada una de las cuales serán pagadas dentro de los cinco (5) primeros días del mes o período y de acuerdo a las políticas de pago del Colegio 
    las cuales hacen parte integral del presente contrato siendo exigible la primera de ellas el día <u>$DIA_EXIGIBLE$</u> y así sucesivamente hasta completar 
    las cuotas señaladas. El costo anual se ajustará cada año según las estipulaciones gubernamentales respectivas y las determinaciones del Consejo 
    Directivo en esta materia. 
    
    <strong>DECIMA. INCUMPLIMIENTO EN EL PAGO:</strong> Hay incumplimiento en el pago cuando: 
    a) Se cancela después del día quinto del comienzo de cada mes; 
    b) Cuando se cancela una cifra o cantidad en dinero inferior al de la obligación, 
    c) cuando el cheque o documento de pago no es abonado por cualquier causa ajena al <strong>COLEGIO</strong>. 
    
    <strong>DECIMA PRIMERA. CONSECUENCIAS DEL INCUMPLIMIENTO EN EL PAGO: </strong>
    Serán consecuencias del incumplimiento en el pago: 
    a) Cancelación después de la fecha. Los <strong>PADRES</strong> del <strong>EDUCANDO </strong>cancelarán los costos educativos 
    y demás cobros más la correspondiente suma de intereses liquidados a la tasa moratoria más alta del mercado financiero y/o establecidas 
    por las autoridades competentes; 
    b) Acumulación de dos meses. Además de lo estipulado en el literal <strong><em>a</em></strong> 
    de esta cláusula, este incumplimiento será causal suficiente para que el <strong>COLEGIO </strong> cancele el cupo escolar del 
    <strong>EDUCANDO</strong> para el año siguiente y emprenda las acciones jurídicas tendientes a hacer efectivo el pago; 
    c) Cheques devueltos. De acuerdo CON EL ART. 731 del C.C. cancelarán el 20% del importe del cheque sin perjuicio que el tenedor 
    persiga por las vías judiciales las indemnizaciones de los daños que ocasionen; 
    d) Incumplimiento de pago por más de dos meses: <strong>EL COLEGIO</strong> o el tenedor del documento garantía o de respaldo que haya 
    establecido <strong> EL COLEGIO </strong> y aceptado en sus partes por el padre o acudiente, iniciará la acción judicial legal para 
    el cobro, sin previo requerimiento; 
    e) Se informará a la entidad de riesgos financieros a la cual estemos adscritos sobre el incumplimiento de pago para el respectivo reporte. 
    
    <strong>DECIMA SEGUNDA. CLÁUSULA DE TERMINACIÓN O DE NO RENOVACIÓN: </strong>
    El presente contrato terminará o se no renovará por las siguientes causas: 
    a) Por expiración del termino fijado o sea el año lectivo <u>$ANNIO_LECTIVO$</u>; 
    b) Por mutuo consentimiento de las partes; 
    c) Por fallecimiento del educando; 
    d) Por suspensión de actividades del colegio por más de sesenta (60) días o por clausura definitiva del establecimiento; 
    e) Por retraso en el pago de pensiones por dos o más meses; 
    f) Por las causas determinadas en el reglamento escolar del establecimiento; 
    g) Por la inasistencia del educando a un 25% de las actividades pedagógicas. Art 53 decreto 1860 de 1994; 
    h) Por cualquiera de las faltas o incumplimiento fijados en el presente contrato y en el Reglamento o Manual de Convivencia. 
    
    <strong>DECIMA TERCERA. PREAVISO: </strong>
    Los <strong>PADRES </strong> del <strong>EDUCANDO </strong> que decidan terminar en forma unilateral el presente contrato 
    deberán informar por escrito a la Dirección del <strong>COLEGIO</strong> su decisión con treinta (30) días de anticipación. 
    En el evento que se produzca el retiro de hecho del <strong>EDUCANDO</strong> sin mediar el preaviso de que aquí se trata, 
    permitirá al <strong>COLEGIO</strong>, seguir cobrando los derechos hasta dos meses más contados a partir del último día 
    del mes en que se produjo el retiro. 
    
    <strong>DECIMA CUARTA. SANCION PENAL: </strong>La terminación unilateral del contrato 
    del servicio educativo por parte de los<strong> PADRES</strong> acarreará el pago inmediato a favor el <strong> COLEGIO </strong>
    del 100% del costo anual total del presente contrato si fuere al inicio del período escolar o el valor faltante del contrato 
    entre la fecha del retiro y la fecha de finalización del contrato. 
    
    <strong> DECIMA QUINTA. </strong>Para cualquier efecto el presente contrato por sí solo presta mérito ejecutivo sin necesidad 
    de requerimientos judiciales y extrajudiciales, renunciando expresamente los <strong>PADRES </strong>al requerimiento para la 
    constitución en mora; y consecuencialmente acuerdan que los costos y demás gastos judiciales y extrajudiciales que se ocasionen 
    por el incumplimiento del presente contrato serán por cuenta de los<strong> PADRES.</strong> 
    
    <strong>DECIMA SEXTA. VIGENCIA Y RENOVACIÓN:</strong> 
    El presente contrato tiene vigencia a partir el día <u>$DIA_INI_VIGENCIA$</u> de febrero de <u>$ANNIO_LECTIVO$</u> hasta el <u>$DIA_FIN_VIGENCIA$</u> 
    de noviembre de <u>$ANNIO_LECTIVO$</u>, su ejecución será sucesiva por periodos mensuales y podrá renovarse para el año siguiente siempre 
    y cuando el <strong> EDUCANDO </strong> y los<strong> PADRES</strong> hayan cumplido estrictamente las condiciones estipuladas 
    en el presente contrato, en el PEI del <strong>COLEGIO</strong> y acepten las condiciones de vinculación. 
    
    <strong>DECIMA SÉPTIMA. ANEXOS: </strong>
    Se consideran parte constitutiva del presente contrato: El PEI y el Reglamento Escolar o Manual de Convivencia.</span>
  
  </div>
  
  <div style="text-align: justify;">
    <br/>
    <span lang="ES" style="font-size: 10pt; font-family: Arial;">
      Para constancia se firma en Valledupar a los <u>$DIA_FIRMA$</u> días del mes de <u>$MES_FIRMA$</u> de <u>$ANNIO_FIRMA$</u>.
    </span>
    <br/><br/><br/>

    <table border="0" cellpadding="0" cellspacing="0" style="text-align: left; width: 100%;">
    <tbody>
      <tr>
        <td valign="top">
          <span lang="ES" style="font-size: 10pt; font-family: Arial;">________________________________________</span>
        </td>
        <td valign="top">
          <span lang="ES" style="font-size: 10pt; font-family: Arial;">________________________________________</span>
        </td>
      </tr>
      
      <tr>
        <td style="vertical-align: top;">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Nombre del Padre de Familia o Acudiente</span>
      </td>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Nombre del Padre de Familia o Acudiente</span>
      </td>
    </tr>
    
    <tr>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">C.C.</span>
      </td>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">C.C.</span>
      </td>
    </tr>
    
    <tr>
      <td style="vertical-align: top;">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Dirección</span>
      </td>
      <td style="vertical-align: top;">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Dirección</span>
      </td>
    </tr>
    
    <tr>
      <td valign="top"></td>
      <td valign="top"></td>
    </tr>

    <tr>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">________________________________________</span>
      </td>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">________________________________________</span>
      </td>
    </tr>

    <tr>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Nombre del Beneficiario - Alumno</span>
      </td>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">MIRIAM CASADIEGO RIOS</span>
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">C.C.</span>
      </td>
    </tr>

    <tr>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">C.C.</span></td>
      <td valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Rectora </span>
      </td>
    </tr>
    
    <tr>
      <td style="text-align: left;" valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">Dirección</span>
      </td>
      <td style="text-align: left;" valign="top">
        <span lang="ES" style="font-size: 10pt; font-family: Arial;">C.C. 57.401.865</span>
      </td>
    </tr>

    </tbody>
    </table>
  
</div>

<p></p>
';