<div class="w3-panel">
  <?= View::Encab($controller_name, $page_action); ?>
  <?= View::flash(); ?>
  
  <div class="w3-row w3-section">
      <?=OdaForm::inputSerach();?>
      <span class="w3-small"><?= 'Total Registros: '.count($data); ?></span><br/>
      
      <table id="myTable" class="w3-table-all w3-responsive w3-hoverable" height:400px;">
      <thead>
         <tr class="w3-theme-d1">
            <th style="width:10%;">Actions</th>
            <th style="width:60%;">Estudiante</th>
            <th style="width:30%;">Cuenta Plataforma</th>
         </tr>
      </thead>
      
      <tbody id="searchBody">      
         <?php foreach($data as $key => $estud) : ?>
            <?php $row_type = ($key%2==0 ) ? 'class="item w3-theme"' : 'class="item w3-theme"' ; ?>
            <tr <?= $row_type?> >
              <td>
                 <?= $estud->getFoto(); ?><br/> 
                 <?= Html::linkAction("estud_edit_activos/$estud->id/", 'Editar');?> <br/>
              </td>
              <td class="searchTdata">
                 <b><u><?= strtoupper($estud->estud);?></u></b> <br/>
                 <span class="w3-margin"><?=$estud->getCodigo()?> <br/> 
                 <span class="w3-margin">[Grado: <?=$estud->grado_mat?>] </br>
                 <span class="w3-margin">Doc: <?=$estud->documento?></span> </br>
                 <span class="w3-margin">Retiro: <?=$estud->fecha_ret?> - Motivo: <?=$estud->retiro?></span> </br>
                 
              </td>
              <td> <?= $estud->getCuentaInstit()?> </td>
            </tr>
         <?php endforeach ?>
      </tbody>
      </table>
      
      
   </div>
   
<?= Tag::js("table_filter"); ?>