<div class="w3-panel">
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
   <?= View::flash(); ?>

   <div class="w3-row w3-section">
      <?=OdaForm::inputSearch();?>
   </div>
   
   <?php 
   try {
      
      foreach ($arrData['Salones'] as $key => $value) {
        echo (new Estudiante)::getLnkListaGenerica($value->id) ;
      }

      $tabla = new OdaTable(theme: $theme, showTotalRegs: true);
      $tabla->setHead(
         data_head:    ['Actions', 'Estudiante', 'Cambiar Salon'], 
         attrs:         'class="w3-theme"', 
         arr_attrs_th: ['style="width:10%;"','style="width:60%;"','style="width:30%;"']
      );
      foreach($data as $key => $Estud) {
         $col1 = $Estud->is_active_f(true) .'<br/>'
                .$Estud->getFoto().'<br/>'
                .$Estud->documento .'<br/>';

        $col2 = "Grado: $Estud->grado_nombre [$Estud->salon_nombre] <br>"
                 ."<h3>{$Estud} {$Estud->isNuevoIco()}</h3>"
                 .$Estud->getCuentaInstit(true).'<br><br>'
                 ."{$Estud->getPagoPension()} {$Estud->getlnkSetPonerAldia()} <br> 
                   {$Estud->getDebePreicfes()} - {$Estud->getDebeAlmuerzos()} <br>"
                 .$Estud->getlnkSetMesPagosTodos().'<br>'
                 .'Boletines '.$Estud->getLnkBoletinesTodos().'<br>'
                 //.$Estud->getLnkPlanesApoyoTodos()
                 ;

         $col3  = $Estud->getSalonesCambiar('secretaria').'<br><br>'
                  .$Estud->madre.' ['.$Estud->madre_id.'] '
                  .OdaUtils::linkWhatsApp(telefono: (string)$Estud->madre_tel_1, show_tel:true)
                  .OdaUtils::linkTelefono(telefono: (string)$Estud->madre_tel_1).'<br><br>'
                  .$Estud->padre.' ['.$Estud->padre_id.'] '
                  .OdaUtils::linkWhatsApp(telefono: (string)$Estud->padre_tel_1, show_tel:true)
                  .OdaUtils::linkTelefono(telefono: (string)$Estud->padre_tel_1).'<br>';
         $data=[$col1, $col2, $col3];
         $tabla->addRow(
            data: $data, 
            attrs_td: ['class="searchTdata w3-center"', 'class="searchTdata"']
         );
      }
      echo $tabla;


    } catch (\Throwable $th) {
      OdaLog::error($th);
      echo $th;
     }

   ?>   
</div>

<?= Tag::js(src: "table_filter"); ?>

<script>
      const inputSearch = document.getElementById("inputSearch").focus();

      document.addEventListener('keydown', function(event) {
        if (event.ctrlKey && event.key === 'b') {
          inputSearch.value = "Segundo";
          inputSearch.select();
        }
      });
</script>