<div class="w3-panel">
  <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
  <?= View::flash(); ?>
  <div class="w3-row w3-section">
    
      <?php
      echo OdaForm::inputSearch();
      $tabla = new OdaTable(theme: $theme);
      $tabla->setHead(
         attrs2:   ['style="width:10%;"','style="width:90%;"'],
      );
      foreach($data as $key => $Estud) {
         $col1 = $Estud->getIsActiveF() .'<br/>'
                .$Estud->getFoto() .'<br/>'
                .Html::linkAction("activarEstudiante/$Estud->id/", 'Activar', 'class="w3-btn w3-green w3-block"').'<br/>';
         
         $col2 = ((!is_null($Estud->nombre_estudiante)) ? strtoupper($Estud->nombre_estudiante) : '').'<br/>'
                .$Estud->getCodigo() .'<br/>' 
                .'[Último Grado: '.$Estud->grado .'</br>'
                .'Doc: '.$Estud->documento.'</br>'
                .'Retiro: '.$Estud->fecha_ret.' - Motivo: '.$Estud->retiro.'</br>';
         
         $tabla->setBody(
            data: [$col1, $col2], 
            attrs2: ['class="searchTdata w3-center"', 'class="searchTdata"']
         );
      }
      echo $tabla;
      ?>
      
   </div>
   
<?= Tag::js("table_filter", false); ?>