<div class="w3-panel">
   <?= View::Encab($controller_name, $page_action); ?>
   <?= View::flash(); ?>
  
   <div class="w3-row w3-section">
      <?=OdaForm::inputSerach();?>
   </div>
   
   <span class="w3-small"><?= 'Total Registros: '.Count($data); ?></span><br/>
   
   <table id="myTable" class="w3-table-all w3-responsive w3-hoverable">
      <thead>
         <tr class="w3-theme">
            <th style="width:10%;">Actions</th>
            <th style="width:60%;">Estudiante</th>
            <th style="width:30%;">Cambiar Salón</th>
         </tr>
      </thead>
      
      <tbody id="searchBody">      
         <?php foreach($data as $key => $estud) : ?>
            <?php $row_type = ($key%2==0 ) ? 'class="item w3-theme"' : 'class="item w3-theme"' ; ?>
            <tr <?= $row_type?> >
              <td>
                 <?= $estud->getFoto(); ?><br/> 
                 <span class="w3-red"> <?= Html::linkAction("estud_edit_activos/$estud->id/", 'Editar '._Icons::solid('pen-to-square', 'w3-large'));?></span>
              </td>
              <td class="searchTdata">
                 <b><u><?= strtoupper($estud->estud);?></u></b> <br/>
                 <span class="w3-margin"><?=$estud->getCodigo()?> <br/> 
                 <span class="w3-margin">[Salon: <?=$estud->salon?>] </br>
                 <span class="w3-margin">Doc: <?=$estud->documento?></span> </br>
                 <span class="w3-margin">Último Mes Pagado: <span class="w3-badge"><?=$estud->mes_pagado?></span>
                 <?php if(!$estud->isPazYSalvo()): ?>
                    <span class="w3-tag w3-green w3-round"><?= Html::linkAction("actualizarPago/$estud->id/", 'Poner al Dia '._Icons::solid('coins', 'w3-large'));?></span>
                 <?php endif; ?>
                 
              </td>
              <td> <?= $estud->getSalonesCambiar('secretaria')?> </td>
         </tr>
         <?php endforeach ?>
      </tbody>
   </table>
   
   
</div>

<?= Tag::js("table_filter"); ?>