<div id="perfil-estud" class="w3-row w3-panel">
   <?= View::flash(); ?>
   <?= View::encab($page_module, $page_title, $set_title); ?>

   <div class="page-inner">
      <header class="page-title-bar">
         <h1 class="page-title"><?=$estudiante;?> </h1>
      </header>
      <div class="page-section">
        <?= Form::open("secretaria/estud_edit_activos/$estudiante->id/", 'post') ?>
        <?= Form::text('nombres', array('placeholder'=>'nada', 'help'=>'nada de help'), $estudiante->nombres);?>
        <?php //form_oda::text_basic($model, 'apellido1'); ?>
        <?php //Form::textarea('apellido1') ?> 
        <?php //Form::text('apellido2') ?>
        <?php //Form::datepicker('fecha_insc') ?>
        <?= Form::submit('Guardar') ?>
        <?= Form::close() ?>
      </div>
   </div>

   <div>
      <?php echo Html::linkAction("estud_list_activos/", 'Volver al Listado') ?>
   </div>

</div>