<div class="w3-panel">
  <?= View::Encab($controller_name, $page_action); ?>
  <?= View::flash(); ?>
  
  <div class="w3-row w3-section">
      <?=OdaForm::inputSerach();?>
      <span class="w3-small"><?="Total Registros: $num_regs"?></span><br/>
      
      <table id="myTable" class="w3-table-all w3-responsive w3-hoverable" height:400px;">
      <thead>
         <tr class="w3-theme-d1">
            <th style="width:10%;"></th>
            <th style="width:60%;">Estudiante</th>
         </tr>
      </thead>
      
      <tbody id="searchBody">
         <?php foreach($data as $key => $Estud) : ?>
            <?php $row_type = ($key%2==0 ) ? 'class="item w3-theme"' : 'class="item w3-theme"' ; ?>
            <tr <?= $row_type?> >
              <td class="w3-center">
                  <?=$Estud->is_active_f()?><br/>
                  <?= $Estud->getFoto(); ?><br/>
                  <div><?= Html::linkAction("activarEstudiante/$Estud->id/", 'Activar', 'class="w3-btn w3-green w3-block"');?> </div><br/>
              </td>
              <td class="searchTdata">
                 <b><u><?= strtoupper($Estud->nombre_estudiante);?></u></b> <br/>
                 <span class="w3-margin"><?=$Estud->getCodigo()?> <br/> 
                 <span class="w3-margin">[Grado: <?=$Estud->grado_mat?>] </br>
                 <span class="w3-margin">Doc: <?=$Estud->documento?></span> </br>
                 <span class="w3-margin">Retiro: <?=$Estud->fecha_ret?> - Motivo: <?=$Estud->retiro?></span> </br>
              </td>
            </tr>
         <?php endforeach ?>
      </tbody>
      </table>
      
      
   </div>
   
<?= Tag::js("table_filter"); ?>