<?php
try {  
  $archivoPDF = new MpdfListasClase([
    'tempDir' => APP_PATH . 'temp/mpdf',
    'format' => 'Legal',
    'orientation' => 'L', // P(portrait), L(landscape) 

    'progressBar' => true,
    'title2annots' => true,  // convert headers in annotations
    'mirrorMargins' => 0,    // mirror the left and right margin values on odd and even pages 
    'exposeVersion' => false, // security 
    
    //'margin_left' => 20,
    //'margin_right' => 15,
    //'margin_top' => 48,
    'margin_bottom' => 25, // no tocar
    'margin_header' => 15, // no tocar
    'margin_footer' => 15, // no tocar
    // more variables in https://mpdf.github.io/reference/mpdf-variables/overview.html
  ]);

  $archivoPDF->SetSubject($file_tipo);
  $archivoPDF->SetTitle($file_title);
  $Nota = new Nota();
  
  $stylesheet = file_get_contents(dirname(__DIR__).'/cargas/style.css');
  $archivoPDF->WriteHTML($stylesheet,\Mpdf\HTMLParserMode::HEADER_CSS);

  foreach ($data as $key => $item) {
    $archivoPDF->AddPage();        
    $tabla = new OdaTable('border=1 width=100%');
    $Caption = $user_nombre_completo .' - '.$item->salon_nombre .' - '.$item->asignatura_nombre.' - Periodo:' .$arrData['periodo'];
    $tabla->setCaption($Caption);
    $archivoPDF->encabezado($tabla);    
    $Notas = $Nota->getBySalonAsignaturaPeriodos(
      $item->salon_id, 
      $item->asignatura_id, 
      [$arrData['periodo']]
    );
    foreach ($Notas as $key => $nota)
    {
      $archivoPDF->cuerpo($tabla, $key, $nota);
    }    
    $archivoPDF->WriteHTML($tabla.$archivoPDF->pie());
  }  
  $archivoPDF->showWatermarkText = false;
  //$dest = ($file_download ? 'D' : 'I');
  $archivoPDF->Output("$file_name.pdf", 'I');
} catch (\Throwable $th) {
  OdaFlash::error($th);
}