
<!--[if lt IE 10]>
<div class="page-message" role="alert">You are using an <strong>outdated</strong> browser. Please <a class="alert-link" href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</div>
<![endif]-->

<main id="comingsoon" class="empty-state empty-state-fullpage bg-primary text-white" style="background-image: url(<?=PUBLIC_PATH?>assets/images/illustration/img-1.png);">
  <div class="empty-state-container">
    <h1 class="state-header" style="letter-spacing: 4px;"> PROCESO DE ADMISIONES <br>Agosto 15 de 2023 <br><br>COMIENZA EN </h1>
    <div id="clock" class="countdown display-1">
      <div class="countdown-item"> 00 <small>Days</small>
      </div>
      <div class="countdown-item"> 00 <small>Hr</small>
      </div>
      <div class="countdown-item"> 00 <small>Min</small>
      </div>
      <div class="countdown-item"> 00 <small>Sec</small>
      </div>
    </div>
    <p class="state-description lead"> <?=Config::get('config.construxzion.name')?> </p>
    <form class="w-75 mx-auto">
      <div class="form-group">
    <div class="input-group bg-white border-white input-group-lg circle">
      <input type="email" class="form-control text-black" placeholder="Your email">
      <div class="input-group-append">
    <button type="submit" class="btn btn-warning circle"><span class="d-none d-sm-inline">Subcribe</span> <span class="d-inline d-sm-none" aria-label="Subcribe"><i class="fa fa-arrow-circle-right"></i></span></button>
      </div>
    </div>
      </div>
    </form>
    <div class="state-action">
      <a href="#" class="btn btn-reset"><i class="fab fa-fw fa-facebook"></i></a> <a href="#" class="btn btn-reset"><i class="fab fa-fw fa-twitter"></i></a> <a href="#" class="btn btn-reset"><i class="fab fa-fw fa-instagram"></i></a> <a href="#" class="btn btn-reset"><i class="fab fa-fw fa-linkedin"></i></a>
    </div>
  </div>
</main>


<!-- BEGIN BASE JS -->
<script src="<?=PUBLIC_PATH?>assets/vendor/jquery/jquery.min.js"></script>
<script src="<?=PUBLIC_PATH?>assets/vendor/popper.js/umd/popper.min.js"></script>
<script src="<?=PUBLIC_PATH?>assets/vendor/bootstrap/js/bootstrap.min.js"></script> <!-- END BASE JS -->
<!-- BEGIN PLUGINS JS -->
<script src="<?=PUBLIC_PATH?>assets/vendor/particles.js/particles.js"></script> <!-- END PLUGINS JS -->
<!-- BEGIN THEME JS -->
<script src="<?=PUBLIC_PATH?>assets/javascript/theme.min.js"></script> <!-- END THEME JS -->
<!-- BEGIN JS -->
<script>
  /**
   * Keep in mind that your scripts may not always be executed after the theme is completely ready,
   * you might need to observe the `theme:load` event to make sure your scripts are executed after the theme is ready.
   */
  $(document).on('theme:init', () =>
  {
/* particlesJS.load(@dom-id, @path-json, @callback (optional)); */
particlesJS.load('comingsoon', '<?=PUBLIC_PATH?>assets/javascript/pages/particles-comingsoon.json');
// Set the date we're counting down to
var countDownDate = new Date('August 15, 2023 06:00:00').getTime();
var countDownFormater = function(i)
{
  return i < 10 ? '0' + i : i;
}
// Update the count down every 1 second
var countDown = setInterval(function()
{
  // Get todays date and time
  var now = new Date().getTime();
  // Find the distance between now an the count down date
  var distance = countDownDate - now;
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
  // Display the result in the element with id='clock'
  document.querySelector('#clock').innerHTML = '' + '<div class="countdown-item">' + countDownFormater(days) + ' <small>Days<\/small><\/div>' + '<div class="countdown-item">' + countDownFormater(hours) + ' <small>Hr<\/small><\/div>' + '<div class="countdown-item">' + countDownFormater(minutes) + ' <small>Min<\/small><\/div>' + '<div class="countdown-item">' + countDownFormater(seconds) + ' <small>Sec<\/small><\/div>';
  // If the count down is finished, write some text
  if (distance < 0)
  {
clearInterval(countDown);
document.querySelector('#clock').innerHTML = 'We\'ll Live Soon';
  }
}, 1000);
  })
</script> <!-- END JS -->