<?php 
try {  
  $tabla = new OdaTable('id="myTable-m" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos de la Madre (Paso 4 de 11)');

  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre'), 
      $FormAspir->getInput(field: 'madre_id'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_edad'), 
      $FormAspir->getInput(field: 'madre_prof'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_empresa'), 
      $FormAspir->getInput(field: 'madre_cargo'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_tel_ofi'), 
      $FormAspir->getInput(field: 'madre_tel_per'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_email'), 
      '', 
      ],
  );
  
  return "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-container\">
      <div class=\"w3-display-topleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'basicos')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'padre')\">Siguiente >></span>
      </div>
      <br/><br/>
      
      {$tabla}

      <br/><br/>
      <div class=\"w3-display-bottomleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'basicos')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'padre')\">Siguiente >></span>
      </div>
    </div>
  </div>";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
