<?php 
try {  
  $tabla = new OdaTable('id="myTable-hp" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Historia Personal (Paso 6 de 11)');

  $tabla->addRow(
    data: [
      $FormAspirPsico->getTextarea(field: 'desfisico'), 
      ],
  );
  
  return "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-container\">
      <div class=\"w3-display-topleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'padre')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'desa_psico')\">Siguiente >></span>
      </div>
      <br/><br/>
      
      {$tabla}

      <br/><br/>
      <div class=\"w3-display-bottomleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'padre')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'desa_psico')\">Siguiente >></span>
      </div>
    </div>
  </div>";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}