<?php 
  $lnk_ley_1581_2012  = OdaTags::linkExterno(Config::get('admisiones.lnk_ley_1581_2012'), 'ley 1581 de 2012');
  $lnk_decreto_1377_2013  = OdaTags::linkExterno(Config::get('admisiones.lnk_decreto_1377_2013'), 'Decreto 1377 de 2013');

  $contenido = "
    <div class=\"card bg-light\">
      <div class=\"card-body overflow-auto\" style=\"height: 100px\">
        <p> Doy mi consentimiento para permitir al <strong>Colegio Windsor</strong> almacenar y procesar mis datos personales de acuerdo 
        a la Política de Tratamiento de Datos. Conforme al derecho al <strong>Habeas Data</strong> reconocido por el artículo 15 de la 
        Constitución Política y desarrollado en la Ley $lnk_ley_1581_2012 y en cumplimiento a lo establecido por 
        el artículo 10 del $lnk_decreto_1377_2013. </p>
      </div>
    </div>
  ";

  $contenido .= "
  <div class=\"form-group\">
    <div class=\"custom-control custom-checkbox\">
      <input type=\"checkbox\" id=\"agreement\" name=\"agreement\" class=\"custom-control-input\" data-parsley-group=\"agreement\" required=\"\"> 
        <label class=\"custom-control-label\" for=\"agreement\">Acepto los términos</label>
    </div>
  </div>
  ";
  
  $contenido .= "
    <hr class=\"mt-5\">
  ";

  $contenido .= "
    <div class=\"d-flex\">
      <!-- <button type=\"button\" class=\"prev btn btn-secondary\">Anterior</button>  -->
      <button type=\"button\" class=\"next btn btn-primary ml-auto\" data-validate=\"agreement\">Siguiente Paso</button>
    </div>
  ";

  return $contenido;
?>