<?php 
$contenido =  ""; 
//$contenido .= '<div class="col-md-6 mb-4">'.$Form->getInput(field:'nombres').'</div>';
// '
// <input 
// type="text" 
// id="firstName" 
// name="firstName" 
// value="" 

// class="form-control" 
// data-parsley-group="datos_basicos" 
// required=""
// > 
// ';

return $contenido;
/*
$tabla .= _open('table', array('width'=>'100%'));
  $tabla .= _tag('tr', $form->getColCampo('nombres') .$form->getColCampo('apellido1') );
  $tabla .= _tag('tr', $form->getColCampo('apellido2') .$form->getColCampo('sexo') );
  $tabla .= _tag('tr', $form->getColCampo('tipo_dcto') .$form->getColCampo('documento') );
  $tabla .= _tag('tr', $form->getColCampo('pais_nac') .$form->getColCampo('depto_nac') );
  $tabla .= _tag('tr', $form->getColCampo('ciudad_nac') .$form->getColCampo('fecha_nac') );
  $tabla .= _tag('tr', $form->getColCampo('direccion') .$form->getColCampo('barrio') );
  $tabla .= _tag('tr', $form->getColCampo('telefono1') .$form->getColCampo('grado_aspira') );
$tabla .= _close('table');
$tabla .= _open('table', array('width'=>'100%'));
  $tabla .= _tag('tr', $form->getColCampo('Aspirantepsico/rel_pad_mad') );
  $tabla .= _tag('tr', $form->getColCampo('Aspirantepsico/vive_con',array('cols'=>'60', 'rows'=>'6')) );
$tabla .= _close('table');
echo $tabla;
*/