<?php 
try {  
  $tabla = new OdaTable();
  $tabla->setCaption('Datos Básicos del Padre');

  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre'), 
      $FormAspir->getInput(field: 'padre_id'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_edad'), 
      $FormAspir->getInput(field: 'padre_prof'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_empresa'), 
      $FormAspir->getInput(field: 'padre_cargo'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_tel_ofi'), 
      $FormAspir->getInput(field: 'padre_tel_per'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_email'), 
      '', 
      ],
  );

  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
