<?php 
try {  
  $info = '<h2>Historia Escolar</h2><p>Información sobre los últimos Jardines y colegios en los que ha estudiando</p>';

  $tabla = new OdaTable('id="myTable-he1" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 1');
  $tabla->addRow(data:[$FormAspir->getInput(field: '1_colegio'),
      $FormAspir->getInput(field: '1_ciudad'),
      $FormAspir->getInput(field: '1_telefono')]);
  $tabla->addRow(data:[$FormAspir->getInput(field: '1_grados'),
      $FormAspir->getInput(field: '1_annios'),
      $FormAspir->getInput(field: '1_motivo_ret')]);
  $info .= $tabla.'<hr>';
  
  $tabla = new OdaTable('id="myTable-he2" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 2');
  $tabla->addRow(data:[$FormAspir->getInput(field: '2_colegio'),
      $FormAspir->getInput(field: '2_ciudad'),
      $FormAspir->getInput(field: '2_telefono')]);

  $tabla->addRow(data:[$FormAspir->getInput(field: '2_grados'),
      $FormAspir->getInput(field: '2_annios'),
      $FormAspir->getInput(field: '2_motivo_ret')]);
  $info .= $tabla.'<hr>';
  
  $tabla = new OdaTable('id="myTable-he3" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 3');
  $tabla->addRow(data:[$FormAspir->getInput(field: '3_colegio'),
      $FormAspir->getInput(field: '3_ciudad'),
      $FormAspir->getInput(field: '3_telefono')]);

  $tabla->addRow(data:[$FormAspir->getInput(field: '3_grados'),
      $FormAspir->getInput(field: '3_annios'),
      $FormAspir->getInput(field: '3_motivo_ret')]);
  $info .= $tabla.'<hr>';

  return $info;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
