<?php 
try {  
  $tabla = new OdaTable('id="myTable-ds" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption("Paso {$num_paso}: Desarrollo Psicológico");

  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'lenguaje')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'aprendizaje')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'comporta')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'afecto')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'autocuidado')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'especialista')]);
  
  return "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-container\">
      <div class=\"w3-display-topleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'{$prev}')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
      </div>
      <br/><br/>
      
      {$tabla}

      <br/><br/>
      <div class=\"w3-display-bottomleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'{$prev}')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
      </div>
    </div>
  </div>";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}

/*
$tabla .= _open('table', array('width'=>'100%'));
  $tabla .= _tag('tr', $FormAspir->getColCampo('Aspirantepsico/rel_pad_mad') );
  $tabla .= _tag('tr', $FormAspir->getColCampo('Aspirantepsico/vive_con',array('cols'=>'60', 'rows'=>'6')) );
$tabla .= _close('table');
echo $tabla;
*/