<?php 
try {  
  $tabla = new OdaTable('id="myTable-fin" class="w3-table w3-responsive w3-striped w3-bordered"');
  
  return "<h2>Fin del formulario</h2>
  <small>Ahora la información se guardará en nuestra base de datos</small>
  <br>
  <small>Nota: para que le permita guardar, debe haber completado al menos los campos obligatorios</small>
  <br>

  <br>
  {$FormAspir->submit('Guardar y Terminar')}
  <br><br>
  ";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}