<?php 
try {  
  $tabla = new OdaTable('id="myTable-af" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption("Paso {$num_paso}: Antecedentes Familiares");

  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'nucleofamil')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'relpadres')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'rel_pad_mad_desc')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'relhermanos')]);
  
  return "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-container\">
      <div class=\"w3-display-topleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'{$prev}')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
      </div>
      <br/><br/>
      
      {$tabla}

      <br/><br/>
      <div class=\"w3-display-bottomleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'{$prev}')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
      </div>
    </div>
  </div>";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}