<?php 
try {  
  $tabla = new OdaTable('id="myTable-ac" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Proceso Académico y otros (Paso 10 de 11)');

  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'proceso_acad')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'relpares')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'reldocentes')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'cumplnormas')]);
  $tabla->addRow(data:[$FormAspirPsico->getTextarea(field: 'porquedesea')]);

  return "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-container\">
      <div class=\"w3-display-topleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'hist_escolar')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'final')\">Siguiente >></span>
      </div>
      <br/><br/>
      
      {$tabla}

      <br/><br/>
      <div class=\"w3-display-bottomleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'hist_escolar')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'final')\">Siguiente >></span>
      </div>
    </div>
  </div>";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
