<?php 
try {  
  $tabla = new OdaTable('id="myTable-p" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos del Padre (Paso 5 de 11)');

  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre'), 
      $FormAspir->getInput(field: 'padre_id'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_edad'), 
      $FormAspir->getInput(field: 'padre_prof'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_empresa'), 
      $FormAspir->getInput(field: 'padre_cargo'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_tel_ofi'), 
      $FormAspir->getInput(field: 'padre_tel_per'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_email'), 
      '', 
      ],
  );

  
  return "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-container\">
      <div class=\"w3-display-topleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'madre')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'hist_pers')\">Siguiente >></span>
      </div>
      <br/><br/>
      
      {$tabla}

      <br/><br/>
      <div class=\"w3-display-bottomleft\"> 
        <span class=\"w3-button\" onclick=\"openTab(event,'madre')\"><< Anterior</span>
        <span class=\"w3-button\" onclick=\"openTab(event,'hist_pers')\">Siguiente >></span>
      </div>
    </div>
  </div>";

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
