<?php 

try { 
  $lnk_ley_1581_2012  = OdaTags::linkExterno(Config::get('admisiones.lnk_ley_1581_2012'), 'ley 1581 de 2012');
  $lnk_decreto_1377_2013  = OdaTags::linkExterno(Config::get('admisiones.lnk_decreto_1377_2013'), 'Decreto 1377 de 2013');

  $btn_check = $FormAspir->getCheck(field: 'is_habeas_data');
  
  $result = "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-topleft\"> 
      <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
    </div>
    <br/><br/>
    <h2>Bienvenido</h2>
    <h3>Paso {$num_paso}: Informe de Privacidad</h3>
    <p> Doy mi consentimiento para permitir al <strong>{$data['institucion_nombre']}</strong> almacenar y procesar mis datos personales de acuerdo 
      a la Política de Tratamiento de Datos.
    </p>
    <p>Conforme al derecho <strong>Habeas Data</strong> reconocido por el <strong>artículo 15 de la 
      Constitución Política</strong> y desarrollado en la <strong>{$lnk_ley_1581_2012}</strong> y <br>
      en cumplimiento a lo establecido por 
      el <strong>artículo 10 del {$lnk_decreto_1377_2013}</strong>. 
    </p>
    </p>{$btn_check}</p>
    <br/><br/>
    <div class=\"w3-display-bottomleft\"> 
      <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
    </div>
  </div>";

  return $result;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
