<?php 
try {  
  $tabla = new OdaTable('id="myTable-db" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption("Paso {$num_paso}: Datos Básicos del Aspirante");

  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'nombres'), 
      $FormAspir->getInput(field: 'apellido1'), 
      $FormAspir->getInput(field: 'apellido2'),
      ''
      ],
  );

  $tabla->addRow(
    data: [$FormAspir->getInput(field: 'fecha_nac'), 
           '<br><b>'.TipoDoc::caption().'</b><br>'.TipoDoc::forSelect('aspirantes_tipo_dcto', 'aspirantes[tipo_dcto]'), 
           $FormAspir->getInput(field: 'documento'),
           ''
          ],
  );

  $tabla->addRow(
    data: ['<br><b>Grado al que Aspira</b><br>'.Grado::getSelectGrados('aspirantes_grado_aspira', 'aspirantes[grado_aspira]'),
           '',
           '<br><b>'.Sexo::caption().'</b><br>'.Sexo::forSelect('aspirantes_sexo', 'aspirantes[sexo]'),
           ''
          ],
  );

  $tabla->addRow(
    data: [$FormAspir->getInput(field: 'pais_nac'), 
           $FormAspir->getInput(field: 'depto_nac'),
           $FormAspir->getInput(field: 'ciudad_nac'),
           ''
          ],
  );
  
  $tabla->addRow(
    data: [$FormAspir->getInput(field: 'direccion'), 
           $FormAspir->getInput(field: 'barrio'),
           $FormAspir->getInput(field: 'telefono1'),
           ''
          ],
  );

  if ('formsencillo'!=$data['tipo_form_admisiones'])
  {
    $tabla->addRow(
      data: [$FormAspirPsico->getTextarea(field: 'rel_pad_mad'), 
            $FormAspirPsico->getTextarea(field: 'vive_con')],
            attrs_td: ['colspan="2"','colspan="2"'],
    );
  }
  

  $extras = $FormAspir->getInput(tipo: 'hidden', field: 'fecha_insc');

  $result = "
  <div class=\"w3-display-container\">
    <div class=\"w3-display-topleft\"> 
      <span class=\"w3-button\" onclick=\"openTab(event,'{$prev}')\"><< Anterior</span>
      <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
    </div>
    <br/><br/>

    {$tabla}
    {$extras}
    
    <br/><br/>
    <div class=\"w3-display-bottomleft\"> 
      <span class=\"w3-button\" onclick=\"openTab(event,'{$prev}')\"><< Anterior</span>
      <span class=\"w3-button\" onclick=\"openTab(event,'{$next}')\">Siguiente >></span>
    </div>
  </div>";

  return $result;

} 

catch (\Throwable $th) 
{
  OdaFlash::error($th);
}