<div class="w3-panel">
<?php

  try {
    $Modelo  = new Aspirante();
    $FormAspir = new OdaForm(modelo: $Modelo, action: 'admin/aspirantes/crear', method: 'post');

    $Modelo  = new AspirantePsico();
    $FormAspirPsico = new OdaForm(modelo: $Modelo, action: 'admin/aspirantes/crear', method: 'post');

    $privacidad    = require('form_info_privacidad.phtml');
    $datos_basicos = require('form_info_basicos.phtml');
    $datos_padre   = require('form_info_padre.phtml');
    $datos_madre   = require('form_info_madre.phtml');
    
    $tabs = new OdaTabs();
    
    $tabs->addTab('privacidad', '1. Privacidad', $privacidad);
    $tabs->addTab('basicos', 'Datos Básicos', $datos_basicos, true);
    $tabs->addTab('madre', 'Info Madre', $datos_madre, true);
    $tabs->addTab('padre', 'Info Padre', $datos_padre, true);

    echo  $FormAspir->getOpenForm().$tabs.$FormAspir->getCloseForm();
  
  } catch (\Throwable $th) {
    OdaFlash::error($th);
  }
  
?>
</div>
