          <!-- .page -->
          <div class="page">
            <!-- .page-inner -->
            <div class="page-inner">
              <!-- .page-title-bar -->
              <header class="page-title-bar">
                <h1 class="page-title"> Bienvenido, Formulario de Admisión para estudiantes nuevos</h1>
                <p class="text-muted"> A continuación, llene la información del formulario. </p>
              </header><!-- /.page-title-bar -->
              <!-- .page-section -->
              <div class="page-section">

                <!-- .section-block -->
                <div class="section-block">

                  <?php 
                  try {
                    $Steeper = new BsTabSteeper();
                    $Modelo = new Estudiante();
                    
                    $Form = new BsForm(
                      _modelo: $Modelo, 
                      _action: 'admin/aspirante/guardar',
                      _method: 'POST',
                      _multipart: true,
                    );

                    $agreement = require('form_privacidad.phtml');
                    $aspi_datos_basicos = require('form_datos_basicos.phtml');

                    $Steeper->addTabStep(
                      ['test-l-1', 'agreement', 'check', 'Privacidad'],
                      ['Aviso de Privacidad', $agreement]
                    );

                    $Steeper->addTabStep(
                      ['test-l-2', 'datos_basicos', 'person', 'Datos Básicos'],
                      ['Datos Básicos del Aspirante', $aspi_datos_basicos]
                    );

                    echo $Steeper;
                  
                  } catch (\Throwable $th) {
                    OdaFlash::error($th);
                  }
                  ?>
                </div><!-- /.section-block -->
              </div><!-- /.page-section -->
            </div><!-- /.page-inner -->
          </div><!-- /.page -->
        
        <!-- .app-footer -->
        <footer class="app-footer">
          <ul class="list-inline">
            <li class="list-inline-item">
              
            </li>
            <li class="list-inline-item">
              
            </li>
            <li class="list-inline-item">
              
            </li>
            <li class="list-inline-item">
              
            </li>
          </ul>
          <div class="copyright"> Copyright © 2023. All right reserved.<br>ConstruxZion Soft </div>
        </footer>
        <!-- /.app-footer -->

    <!-- BEGIN BASE JS -->
    <script src="<?=PUBLIC_PATH?>assets/vendor/jquery/jquery.min.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/popper.js/umd/popper.min.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/bootstrap/js/bootstrap.min.js"></script> <!-- END BASE JS -->
    <!-- BEGIN PLUGINS JS -->
    <script src="<?=PUBLIC_PATH?>assets/vendor/pace-progress/pace.min.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/stacked-menu/js/stacked-menu.min.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/parsleyjs/parsley.min.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/vanilla-text-mask/vanillaTextMask.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/text-mask-addons/textMaskAddons.js"></script>
    <script src="<?=PUBLIC_PATH?>assets/vendor/bs-stepper/js/bs-stepper.min.js"></script> <!-- END PLUGINS JS -->
    <!-- BEGIN THEME JS -->
    <script src="<?=PUBLIC_PATH?>assets/javascript/theme.min.js"></script> <!-- END THEME JS -->
    <!-- BEGIN PAGE LEVEL JS -->
    <script src="<?=PUBLIC_PATH?>assets/javascript/pages/steps-demo.min.js"></script> <!-- END PAGE LEVEL JS -->
