<div class="w3-container w3-row w3-bar">
  <div class="w3-bar-item">
    <p>Por favor, haga una revisión del formulario antes de diligenciarlo para asegurarse que tiene la información que se requiere para poder completarlo correctamente.</p>
    <p>Descargue y diligencie el Formato de Autorización Consulta y Reporte a Centrales de Riesgo <?=OdaTags::link('files/download/matriculas/windsor_formato_actualizacion.pdf', 'DESCARGAR', 'target="_blank"')?>, al final tendrá que adjuntarlo.<p>
  </div>  
</div>