<div class="w3-panel">
  <?php 
  try {    
    require('indexHeader.phtml');
    
    echo OdaForm::inputSearch();
    if ($tot_regs = count($data)) {
      $tabla = new OdaTable();
      $tabla->setHead(['Acciones', ...$fieldsToShowLabels]);
      foreach ($data as $key => $item_data) {
        $uuid_ok   = (property_exists($item_data, 'uuid') && strlen($item_data->uuid)>0);
        $edit_id   = ($uuid_ok) ? "editUuid/$item_data->uuid" : "edit/$item_data->id";
        $delete_id = ($uuid_ok) ? "delUuid/$item_data->uuid" : "del/$item_data->id";
        
        $msg_name  = strtoupper($nombre_modelo.': '.((property_exists($item_data, 'nombre')) ? $item_data->nombre : " # $item_data->id")) ;
        
        $lnkEditar = OdaTags::linkIcon(action: "admin/$controller_name/$edit_id", icon: 'square-pen', attr: 'title="Editar Registro"');
        $lnkBorrar = Html::linkAction($delete_id, _Icons::solid('trash-can'), 
          'title="Eliminar Registro" onclick="return confirm(\'Atención: ¿Quiere eliminar? \n'.$msg_name.'\')"');

        $arrFields = [];
        foreach ($fieldsToShow as $key => $field) {
          //$arrFields[]= (('is_active'==$field)? $item_data->is_active_f(true): $item_data->$field);
          $dato = $item_data->$field;
          if ('is_active'==$field) {
            $dato = $item_data->is_active_f(true);
          }

          if ('nombre'==$field) {
            $dato = '['.$item_data->id.'] '.OdaUtils::nombrePersona((string)$item_data->$field);
          }

          if (str_ends_with($field, '_id')) {
            $field_with_name = substr($field, 0, strlen($field)-3).'_nombre';
            if (isset($item_data->$field_with_name) and (!is_null($item_data->$field_with_name))) {
              $dato = '['.$item_data->$field.'] '.OdaUtils::nombrePersona($item_data->$field_with_name);
            } else {
              $dato = '['.$item_data->$field.'] '.$item_data->$field;
            }
          }
          $arrFields[] = $dato;
        }

        $arrBody = [$lnkEditar.'&nbsp;&nbsp;'.$lnkBorrar, ...$arrFields];
        $tabla->addRow($arrBody, attrs_td: [null, null, 'class="searchTdata"', 'class="searchTdata"']);
      }
      echo $tabla;
      echo "<h4>Total Registros: $tot_regs</h4>";
    }
    require('indexFooter.phtml');
  } catch (\Throwable $th) {
    OdaFlash::error($page_action.PHP_EOL.$th, true, __CLASS__.'->'.__FUNCTION__.', Line: '.__LINE__);
  }
  ?>
</div>

<script>
      document.getElementById("inputSearch").focus();

      document.addEventListener('keydown', function(event) {
        if (event.ctrlKey && event.key === 'b') {
          document.getElementById('inputSearch').select();
        }
      });
</script>