<h2>Agregando Nuevo Registro</h2>
<?php
$model = new RegistroDesempAcad();
$fieldsToHidden = $model::getFieldsHidden('create');
$titulo = '<h3 id="nombre_estud_new"></h3>';

$myForm = new OdaForm($model, 'admin/registros_desemp_acad/create_ajax', multipart: true);
  $myForm->setAtrib('id="frm_new" name="frm_new"');
  $myForm->setColumnas(2);
  $myForm->addSelect(field:'periodo_id', columna:1, data: OdaUtils::PERIODOS);
  $myForm->addInput(field:'fecha', columna:1, tipo:'date');
  
  $myForm->addTextarea(field:'fortalezas', columna:1);
  $myForm->addTextarea(field:'dificultades', columna:1);
  $myForm->addTextarea(field:'compromisos', columna:1);

  $myForm->addInput(field:'acudiente', columna:2, tipo:'text');
  $myForm->addFile(field:'foto_acudiente', columna:2);
  $myForm->addInput(field:'director', columna:2, tipo:'text');
  $myForm->addFile(field:'foto_director', columna:2);
  
  $myForm->addHiddens(implode(",", $fieldsToHidden));
  
  return "<div class=\"w3-container\">$titulo $myForm</div>";
?>