<?php
  $links_docente = 
   OdaTags::linkBarItem('docen-carga-academica', 'Mi Carga', 'people-line')
  .OdaTags::linkBarItem('docen-reg-observaciones', 'Observaciones', 'address-card');

  if ( Session::get('es_director') ) {
    $links_docente .= OdaTags::linkBarItem('docen-dir-grupo', 'Mi Grupo', 'clipboard');
  }
  
?>

<div class="w3-bar-block">
   <?= $links_docente ?>
</div>

<?php if(Session::get('roll')=='coordinadores'): ?>
   <details class="w3-padding">
      <summary> <u>Coordinación</u> </summary>
      <?php View::partial("coordinador/coordinador_menu") ?>
   </details>     
<?php endif; ?>