   <details class="w3-padding">
      <summary> <u>Docentes</u> </summary>
      <?= _Tag::linkBarItem('docentes/index', 'Index') ?>
      <?php View::partial("docentes/docentes_menu") ?>
   </details>
   
   <details class="w3-padding">
      <summary> <u>Coordinación</u> </summary>
      <?= _Tag::linkBarItem('coordinador/index', 'Index') ?>
      <?php View::partial("coordinador/coordinador_menu") ?>
   </details>

   <details class="w3-padding">
      <summary> <u>Contabilidad</u> </summary>
      <?= _Tag::linkBarItem('contabilidad/index', 'Index') ?>
      <?php View::partial("contabilidad/contabilidad_menu") ?>
   </details>

   <details class="w3-padding">
      <summary> <u>Secretaria</u> </summary>
      <?= _Tag::linkBarItem('secretaria/index', 'Index') ?>
      <?php View::partial("secretaria/secretaria_menu") ?>
   </details>

   <details class="w3-padding">
      <summary> <u>Sicologia</u> </summary>
      <?= _Tag::linkBarItem('sicologia/index', 'Index') ?>
      <?php View::partial("sicologia/sicologia_menu") ?>
   </details>

   <details class="w3-padding">
      <summary> <u>Padres</u> </summary>
      <?= _Tag::linkBarItem('padres/index', 'Index') ?>
      <?php View::partial("padres/padres_menu") ?>
   </details>

   <details class="w3-padding">
      <summary> <u>Enfermeria</u> </summary>
      <?= _Tag::linkBarItem('enfermeria/index', 'Index') ?>
      <?php View::partial("enfermeria/enfermeria_menu") ?>
   </details>

   <details class="w3-padding">
      <summary><u>CONFIGURACIÓN</u></summary>
         
         <details class="w3-padding">
            <summary><u>Tablas</u></summary>
            <?= _Tag::linkBarItem('', 'Secciones', '') ?>
            <?= _Tag::linkBarItem('', 'Areas', '') ?>
            <?= _Tag::linkBarItem('admin/grados', 'Grados', '') ?>
            <?= _Tag::linkBarItem('', 'Salones', '') ?>
         </details>
         
         <details class="w3-padding">
            <summary><u>Usuarios</u></summary>
            <?= _Tag::linkBarItem('', 'Padres', '') ?>
            <?= _Tag::linkBarItem('', 'Docentes', '') ?>
            <?= _Tag::linkBarItem('', 'Administrativos', '') ?>
         </details>
         
         <details class="w3-padding">
            <summary><u>Configuraciones</u></summary>
            <?= _Tag::linkBarItem('', 'Períodos Académicos', '') ?>
            <?= _Tag::linkBarItem('', 'Asignar Cargas', '') ?>
         </details>

      </details>
      
      
   <details class="w3-padding">
      <summary><u>Ayudas</u></summary>
      <?= _Tag::linkBarItem('pages/kumbia/status', 'Status Kumbia', '') ?>
      <?= _Tag::linkBarItem('pages/status_app', 'Check General', '') ?>
      <?= _Tag::linkBarItem('pages/ayuda', 'Ayuda del Sistema', '') ?>
      <?= _Tag::linkBarItem('pages/colores', 'Colores W3', '') ?>         
      <?= _Tag::linkBarItem('pages/iconos', 'Íconos FA', '') ?>         
   </details>
      
   <details class="w3-padding">
      <summary><u>Pruebas de Código</u></summary>
      <?= _Tag::linkBarItem('ejemplo', 'Index', '') ?>
      <?= _Tag::linkBarItem('ejemplo/excel', 'Excel', '') ?>
      <?= _Tag::linkBarItem('ejemplo/validaciones', 'Validaciones Forms', '') ?>
      <?= _Tag::linkBarItem('ejemplo/archivos', 'Archivos', '') ?>
   </details>