<?php 

  $tabla = new OdaTable(theme:'light', _attrs: 'class="w3-table w3-striped w3-border w3-bordered"');
  $tabla->setCaption($pdf_title);
  $tabla->setHead(
    data_head: ['Id', 'Salon', 'Grado', 'Director'],
    arr_attrs_th:['class="w3-theme"', 'class="w3-theme"', 'class="w3-theme"', 'class="w3-theme"']
  );
  foreach ($data as $item) {
    $tabla->addRow( data:[$item->id, $item->nombre, $item->grado_nombre, $item->director_nombre] );
  }
  echo $tabla;

?>
