<?php 
try {
  $header = [
    'Activo'      => 'integer', 
    'Salón'       => 'string', 
    'Grado'       => 'string', 
    'Director'    => 'string', 
    'Codirector'  => 'string', 
    'Estudiantes' => 'integer', 
  ];

  $fileds_names = [
    'Activo'      => 'is_active', 
    'Salón'       => 'nombre', 
    'Grado'       => 'grado_nombre', 
    'Director'    => 'director_nombre', 
    'Codirector'  => 'codirector_nombre', 
    'Estudiantes' => 'tot_estudiantes',
  ];
  
  foreach ($registros as $item) {
    $columnas = [];
    foreach ($header as $title_name => $title_type) {
      $campo = $fileds_names[$title_name];
      $columnas[] =  ('integer'==$title_type) ? (int)$item->$campo : $item->$campo;
    }
    $data[] = (array)$columnas;
  }

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
  
?>