<?php
  View::partial(partial: 'header_views', params: ['controller'=>$controller_name, 'page'=>$page_action] );

  $RegAsignatura = $arrData['asignatura'];
  $RegGrado = $arrData['grado'];
?>

<div class="w3-container">
   <h2> <?="<b>$RegAsignatura</b> -- <b>Grado $RegGrado->nombre</b>"?> </h2>
   <?php
      $Tabs = new OdaTabs();
      foreach ($data as $periodo => $regs_periodo) {
         $tabla = new OdaTable(showTotalRegs: true);
         $lnk_button_new = OdaTags::linkButton('docentes/indicadores/edit/edit', "Crear Nuevo Indicador P$periodo").'<br>';
         foreach ($regs_periodo as $key => $indic) {
            $cod = "<u>P$periodo - $indic->codigo [$indic->valorativo] </u><br>";
            $datos=array($cod.$indic->concepto);
            $tabla->setBody($datos);
         }
         $Tabs->addTab("p$periodo", "Periodo $periodo", $lnk_button_new.$tabla);
      }
      echo $Tabs;
   ?>
</div>

<?= tag::js("tabs_h", true);?>