<template id="btn_new_template">
  <div class="w3-padding">
    <button id="id_btn_new" class="w3-btn w3-green" onclick="show_new_form()">Nuevo Indicador P{periodo}</button>
  </div>
</template>

<template id="table_template">
  <table id="myTable" class="w3-table w3-responsive w3-striped w3-bordered">
    <tbody id="searchBody"></tbody>
  </table>
</template>

<template id="new_row_template">
  <tr class="item w3-theme-d4">
    <td> 
      <a href="/edsa-schoolnext/admin/indicadores/del/177382/docentes.listIndicadores.9.10"><i class="fa-solid fa-trash-can w3-large"></i></a>
      <b></b><br>
      <p></p>
  </td>
  </tr>
</template>

<?php
  View::partial(partial: 'header_views', params: ['controller'=>$controller_name, 'page'=>$page_action] );
  return "<h2>Grado $RegGrado->nombre: $RegAsignatura->nombre</h2>";
?>