<?php
  $model = new Indicador;
  $myForm = new OdaForm($model, 'admin/indicadores/create_ajax');
          $myForm->setAtrib('id="form_new"');
          $myForm->addInput(1,'number','codigo');
          $myForm->addInput(1,'text','concepto');
          $myForm->addSelect(1,'valorativo', $model::$valorativos);
          $myForm->addHiddens('annio, periodo_id, grado_id, asignatura_id, is_active, is_visible, created_by, updated_by, created_at, updated_at');
  return "<div class=\"w3-container\" id=\"formulario\" style=\"display: none;\">$myForm cancelar</div>";
?>
