<?php 
$RegAsignatura = $arrData['asignatura'];
$RegGrado = $arrData['grado'];
$buttons = [];
  for ($i=1; $i<=5; $i++) { 
    $buttons[$i] = ['caption'=>"Periodo $i", 'action'=>"traer_data($i,$RegGrado->id,$RegAsignatura->id)"];
  }
  $botones = OdaTags::buttonBars($buttons);
?>

<div class="w3-container">
  <?php echo require('listHeader.phtml') ?>
  <?php echo require('listForm.phtml') ?>
  <div id="lista_indicadores" class="">
    <div id="botones"><?= $botones ?></div>
    <div id="capa_datos">
      </div>
    </div>
  <?php echo require('listFooter.phtml') ?>
</div>

<?= Tag::js("docentes/indicadores_list", false); ?>