<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, 'Utilidades de Kumbia', ''); ?>
</div>


<div class="w3-container">
<?php

try {
  //code...
  

  $tabla = new OdaTable(searchCol: [1,2], showTotalRegs: true);
  $tabla->setHead(data_head: ['Clase', 'M&eacute;todos'], arr_attrs_th: ['style="width:50%"', 'style="width:50%"']);
  
  $tabla->setCaption(caption:'CONSTANTES');
  $arrConstantes = [
    'PRODUCTION'            => ((PRODUCTION) ? 'SI' : 'NO: DESARROLLO'), 
    'PUBLIC_PATH'           => PUBLIC_PATH, 
    '[PATH_INFO] server'    => $_SERVER['PATH_INFO'],
    'ABS_PUBLIC_PATH'   => ABS_PUBLIC_PATH,
    'CORE_PATH'   => CORE_PATH,
    'APP_NAME'   => APP_NAME,
    'FILE_UPLOAD_PATH'   => FILE_UPLOAD_PATH,
    'FILE_DOWNLOAD_PATH'   => FILE_DOWNLOAD_PATH,
    'IMG_UPLOAD_PATH'   => IMG_UPLOAD_PATH,
    'IMG_DOWNLOAD_PATH'   => IMG_DOWNLOAD_PATH,
    'SCHOOLWEB_PUBLIC_PATH'   => SCHOOLWEB_PUBLIC_PATH,
  ];

  foreach ($arrConstantes as $key => $K) {
    $tabla->addRow(data:[$key, "<strong class=\"w3-white w3-text-red\">&nbsp&nbsp $K &nbsp&nbsp</strong>"]);
  }

  // VARIABLES DE ENTONRNO
  // ======================
  $arrEnvirVars = [
  //$_SERVER['HTTP_HOST']	windsor.schoolnext.space o 127.0.0.1
  //$_SERVER['HTTP_REFERER']	https://windsor.schoolnext.space/admin 
  //$_SERVER['REDIRECT_SSL_TLS_SNI']	windsor.schoolnext.space
  //$_SERVER['SSL_TLS_SNI']	windsor.schoolnext.space
  //SERVER['SERVER_NAME']	windsor.schoolnext.space o 127.0.0.1
  //$_SERVER['SERVER_ADDR']	162.241.253.15
  //$_SERVER['SERVER_PORT']	443
  //$_SERVER['REMOTE_ADDR']	186.169.76.68
  //$_SERVER['DOCUMENT_ROOT']	/home2/dwsjrnmy/public_html/windsor_schoolnext_public
  //$_SERVER['REQUEST_SCHEME']	https
  //$_SERVER['CONTEXT_DOCUMENT_ROOT']	/home2/dwsjrnmy/public_html/windsor_schoolnext_public
  //$_SERVER['SERVER_ADMIN']	webmaster@windsor.schoolnext.space
  //$_SERVER['SCRIPT_FILENAME']	/home2/dwsjrnmy/public_html/windsor_schoolnext_public/index.php
  //$_SERVER['REMOTE_PORT']	59013
  //$_SERVER['REDIRECT_URL']	/pages/check
  //$_SERVER['SERVER_PROTOCOL']	HTTP/2.0
  //$_SERVER['REQUEST_METHOD']	GET
  //$_SERVER['QUERY_STRING']	no value
  //$_SERVER['REQUEST_URI']	/pages/check
  //$_SERVER['SCRIPT_NAME']	/index.php
  //$_SERVER['PATH_INFO']	/pages/check
  //$_SERVER['PATH_TRANSLATED']	redirect:/index.php/pages/check/check
  //$_SERVER['PHP_SELF']	/index.php


  //$_SERVER['HTTP_HOST']	
  //SERVER['SERVER_NAME']	127.0.0.1
//$_SERVER['SERVER_ADDR']	127.0.0.1
//$_SERVER['SERVER_PORT']	80
//$_SERVER['REMOTE_ADDR']	127.0.0.1
//$_SERVER['DOCUMENT_ROOT']	C:/EasyPHP-Devserver-17/eds-www
//$_SERVER['REQUEST_SCHEME']	http
//$_SERVER['CONTEXT_PREFIX']	/edsa-schoolnext
//$_SERVER['CONTEXT_DOCUMENT_ROOT']	D:/schoolnext/frontend/public
//$_SERVER['SERVER_ADMIN']	admin@example.com
//$_SERVER['SCRIPT_FILENAME']	D:/schoolnext/frontend/public/index.php
//$_SERVER['REMOTE_PORT']	58998
//$_SERVER['REDIRECT_URL']	/edsa-schoolnext/pages/check
//$_SERVER['REQUEST_METHOD']	GET
//$_SERVER['QUERY_STRING']	no value
//$_SERVER['REQUEST_URI']	/edsa-schoolnext/pages/check
//$_SERVER['SCRIPT_NAME']	/edsa-schoolnext/index.php
//$_SERVER['PATH_INFO']	/pages/check
//$_SERVER['PATH_TRANSLATED']	C:\EasyPHP-Devserver-17\eds-www\pages\check
//$_SERVER['PHP_SELF']	/edsa-schoolnext/index.php/pages/check

  ];
  // =====================================================
  // =====================================================
  // =====================================================
  $arrClassNames = [
    ['OdaUtils', 'OdaFile', 'FileUtil'],      
    ['OdaAjax', 'OdaJs', 'OdaTags'], 
    ['OdaLog', 'OdaFlash', 'Html'],           
    ['OdaTable', 'OdaTabs', ''],
    ['', 'OdaPdf', 'OdaExcel'],        
    ['Breadcrumb', 'I18n', 'Css'],
    ['ModelForm', '', ''],
    ['KumbiaRouter', '', 'KumbiaView'], 
    ['KumbiaException', 'Router', 'Console'], 
    ['SimpleAcl', 'Acl2', 'Auth2Odair'],
    ['Filter', 'Input', 'Redirect'],          
    ['Rest', 'Session', 'Upload'],
    ['Validate', 'Validations', ''],
    //['', '', ''],
  ];
  
  $arrClassManuales = [
    //'controller' => ['','',],
    'admin_controller' => [
      '$page_action','$page_title','$breadcrumb',
      '$theme','$themei','$user_id','$user_name',
      '$page_module','$id_instit','public array  $arrData','public object $Modelo',
      'public array  $fieldsToShow','public array  $fieldsToShowLabels','public array  $fieldsToHidden',
      '$nombre_post','$nombre_modelo',],
      
      'app_controller' => [
        '$page_action','$page_title','$breadcrumb',
        '$theme','$themei','$user_id','$user_name','$_data_count',
        '$page_module','$id_instit','public array  $arrData','public object $Modelo',
        'public array  $fieldsToShow','public array  $fieldsToShowLabels','public array  $fieldsToHidden',
        '$nombre_post','$nombre_modelo',
      ],
  ];
  

  foreach ($arrClassManuales as $class_name => $propiedades) {
    $str_props = '';
    foreach ($propiedades as $prop) {
      $prop_nombre = "<span class=\"w3-tag w3-teal\">$prop</span>";
      $str_props .= $prop_nombre.', ';
    }
    $tabla->addRow([$class_name, '<b>Propiedades</b><br>'.$str_props], attrs_td:['class="searchTdata"', 'class="searchTdata"']);
  }


  //
  function class_tags($elemento) { return "<span class=\"w3-tag\">$elemento</span>"; }
  $elements_searchs = '';
  foreach ($arrClassNames as $fila) { 
      $a = array_map("class_tags", $fila);
      $elements_searchs .= (empty($a)) ? '' :  implode(' ', $a).' ';

    $Columnas = [];
    foreach ($fila as $key => $class_name) { // las tres clases en cada fila
      if ($class_name) {

        $vars = '';
        try { // PROPIEDADES
          $class_vars = get_class_vars(get_class(new $class_name()));
          foreach ($class_vars as $name => $value) { 
            $vars .= "<span class=\"w3-tag w3-teal\">$name : $value, </span> ";
          }
          if ($vars) { 
            $tabla->addRow([$class_name, '<b>Propiedades</b><br>'.$vars], attrs_td:['class="searchTdata"', 'class="searchTdata"']);
          }
        } catch (\Throwable $th) {
          OdaFlash::warning($th);
        }

        $methods = '';
        try { // MÉTODOS DE LACLASE
          $metodos_clase = get_class_methods(new $class_name());
          foreach ($metodos_clase as $key => $nombre_metodo) {
            $methods .= ($key+1).".  $class_name::$nombre_metodo()<br>";
            $metodo_nombre = "<strong class=\"w3-white w3-text-red\">&nbsp&nbsp$nombre_metodo()&nbsp&nbsp</strong>";
            $tabla->addRow([$class_name, $metodo_nombre], attrs_td:['class="searchTdata"', 'class="searchTdata"']);
          }
        } catch (\Throwable $th) {
          $tabla->addRow([$class_name,"Error: no es posible cargar los métodos de esta clase."]);
          $methods .= "Error en $class_name $th"; //throw $th;
        }
        $Columnas[$key] = "<h3>$class_name</h3> <br> $methods";

      } else {
        $Columnas[($key+1).$class_name] = "<hr>";
      }  
    }
  }

  echo 
    '<div class="w3-row">'
      .$elements_searchs
      .OdaForm::inputSearch()
      .$tabla
    .'</div>';


  } catch (\Throwable $th2) {
    OdaFlash::error($th2);
  } finally {

  }

?>
</div>

<?=Tag::js("table_filter", false);?>