<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, $page_action); ?>
</div>

<div class="w3-container">
<?php
try {
  $Modelo = (new Grado());
  foreach ($Modelo::all() as $key => $obj) {
    $uuid = $obj->xxh3Hash();
    
    $DQL = new OdaDql($Modelo::class);
    $DQL->update(['uuid' => $uuid])
      ->where("id=?")
      ->setParams([$obj->id])
      ->execute(true);

    echo $DQL." $obj->id<br>";
  }

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
?>

</div>