<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, 'Acerca de SchoolNext>>', ''); ?>
</div>

<div class="w3-container">
  <div class="w3-row">
    
    <div class="w3-half">
      <p class="w3-padding">SchoolNext>> es una aplicación web moderna para la gestión de Colegios que usa tecnologías avanzadas en el backend y en la interfaz de usuario. Lo que la convierte en una herramienta ágil para las tareas del día a día</p>
      
      <h2>Tecnologías utilizadas</h2>
      <ul class="w3-ul">
        <li class="w3-">Diseño Web Adaptable (Responsive Web Design): Se adapta a todo tipo de medios, pantallas y dispositivos.</li>
        <li class="w3-">La interfaz de usuario es muy intuitiva y por ende muy fácil de usar.</li>
      </ul>

    </div>



    <div class="w3-half">
      <h2>Ventajas</h2>
      
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Es un software ultra rápido</dt>
        <dd>¿porqué es tan rápido y que ventajas competitivas tiene?.</dd>
      </dl>

      <dl class="w3-ul w3-card-4 w3-theme-d3">
        <dt>Muy intuitiva Interfaz de Usuario (UI)</dt>
        <dd>Es una aplicación muy fácil de utilizar en cualquier dispositivo</dd>
      </dl>

      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Agilidad en los procesos rutinarios</dt>
        <dd>Califica en menos tiempo posible y sin errores.</dd>
      </dl>
    </div>
    
  </div>
</div>