<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, 'Acerca de SchoolNEXT>>', ''); ?>
</div>

<div class="w3-container">

  <div class="w3-row w3-container">
    <p>
      <b>SchoolNEXT>></b> Es una Aplicación Web moderna para la Gestión de Colegios, que usa tecnologías avanzadas en el backend y en la interfaz de usuario. 
        Lo que la convierte en una herramienta muy ágil para realizar las tareas del día a día de todos los usuarios que pertenecen a la institución.
    </p>
    <h3>Características del Software</h3>
    <ul class="w3-ul">
      <li class="w3-">Es un software ultra rápido.</li>
      <li class="w3-">Tiene un diseño web adaptable: Se adapta a todo tipo de medios, pantallas y dispositivos.</li>
      <li class="w3-">La interfaz de usuario es muy intuitiva y por ende muy fácil de usar.</li>
      <li class="w3-">Hecho a la medida de la institución.</li>
    </ul>
  </div>

  <div class="w3-row w3-container">
      <h2>Objetivos </h2>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Gestión de estudiantes</dt><dd> El programa debe permitir la gestión de la información de los estudiantes, como su nombre completo, fecha de nacimiento, dirección, historial académico, asistencia, comportamiento y notas. También debe permitir la creación de perfiles individuales de los estudiantes.</dd>
      </dl>
      <br>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Gestión de profesores</dt><dd> El programa debe permitir la gestión de la información de los profesores, como su nombre completo, áreas de enseñanza, horarios de clases y contactos. También debe permitir la creación de perfiles individuales de los profesores.</dd>
      </dl>
      <br>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Gestión de asignaturas y planes de estudios</dt><dd> El programa debe permitir la gestión de las asignaturas y planes de estudios, incluyendo el número de horas asignadas a cada asignatura, los objetivos de aprendizaje y los criterios de evaluación.</dd>
      </dl>
      <br>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Gestión de calificaciones y evaluaciones</dt><dd> El programa debe permitir la gestión de las calificaciones y evaluaciones de los estudiantes, incluyendo la creación de exámenes y la introducción de notas. También debe permitir la generación de informes de calificaciones y evaluaciones para los estudiantes y los padres.</dd>
      </dl>
      <br>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Comunicación y colaboración</dt><dd> El programa debe permitir la comunicación y la colaboración entre los estudiantes, los profesores y los padres, incluyendo la publicación de anuncios, el envío de correos electrónicos y la organización de reuniones. También debe permitir la creación de foros de discusión y la compartición de recursos.</dd>
      </dl>
      <br>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Seguridad y privacidad</dt><dd> El programa debe garantizar la seguridad y la privacidad de la información de los estudiantes, los profesores y los padres, incluyendo la protección de datos personales y la prevención del acceso no autorizado.</dd>
      </dl>
      <br>
      <dl class="w3-ul w3-card-4 w3-theme-d1">
        <dt>Accesibilidad y usabilidad</dt><dd> El programa debe ser accesible y fácil de usar para todos los usuarios, incluyendo los estudiantes, los profesores y los padres. También debe ser compatible con diferentes dispositivos y sistemas operativos, y tener una interfaz intuitiva y fácil de entender.</dd>
      </dl>
      <br>
  </div>

</div>