
   <h1>Help</h1>
   <?= _Tag::meter(10, 'Titulo') ?>
   <?= _Icons::solid('flag', 'w3-xxxlarge') ?>

<?php
      list($id, $name, $value) = array(1,2,3);
      echo $id.'-'.$name.'-'.$value;

      $array = ['locality' => 'Tunis', 'postal_code' => '1110'];
      list('postal_code' => $zipCode, 'locality' => $locality) = $array;
      print $zipCode; // will output 1110
      print $locality; // will output Tunis

   $names = array('Jesse', 'joey', 'jelnny', 'justine');
   $names = new ArrayObject($names);

   echo '<pre>';
   print_r($names);
   echo '</pre>';

   $tabla = new OdaTable();
   $tabla->setHead('col 1, col 2, col 3')
            ->setBody('data 1-1, col 1-2, col 1-3')
            ->setBody('data 2-1, col 2-2, col 2-3')
            ->setBody('data 3-1, col 3-2, col 3-3')
         ->setFoot(['--', 'Fin', '--']);
   echo $tabla;
?>