<h1><?=$theme?></h1>

<div class="w3-row">

   <div class="w3-container w3-third">
      <h2>Tema 2</h2>
      <div class="w3-panel w3-theme">w3-theme</div>
      <div class="w3-panel w3-theme-light">w3-theme-light</div>
      <div class="w3-panel w3-theme-dark">w3-theme-dark</div>
      <div class="w3-panel w3-theme-action">w3-theme-action</div>
      <div class="w3-panel w3-border">w3-text-theme w3-border-theme</div>
      <div class="w3-panel"><hr></div>
      <div class="w3-panel w3-theme-l5">w3-theme-l5</div>
      <div class="w3-panel w3-theme-l4">w3-theme-l4</div>
      <div class="w3-panel w3-theme-l3">w3-theme-l3</div>
      <div class="w3-panel w3-theme-l2">w3-theme-l2</div>
      <div class="w3-panel w3-theme-l1">w3-theme-l1</div>
      <div class="w3-panel w3-theme-d1">w3-theme-d1</div>
      <div class="w3-panel w3-theme-d2">w3-theme-d2</div>
      <div class="w3-panel w3-theme-d3">w3-theme-d3</div>
      <div class="w3-panel w3-theme-d4">w3-theme-d4</div>
      <div class="w3-panel w3-theme-d5">w3-theme-d5</div>
   </div>
   
      
   <div class="w3-container w3-third">
      <h2>Tema 2</h2>
      <div class="w3-panel w3-theme2">w3-theme2</div>
      <div class="w3-panel w3-theme2-light">w3-theme2-light</div>
      <div class="w3-panel w3-theme2-dark">w3-theme2-dark</div>
      <div class="w3-panel w3-theme2-action">w3-theme2-action</div>
      <div class="w3-panel w3-border2">w3-text-theme2 w3-border-theme2</div>
      <div class="w3-panel"><hr></div>
      <div class="w3-panel w3-theme2-l5">w3-theme2-l5</div>
      <div class="w3-panel w3-theme2-l4">w3-theme2-l4</div>
      <div class="w3-panel w3-theme2-l3">w3-theme2-l3</div>
      <div class="w3-panel w3-theme2-l2">w3-theme2-l2</div>
      <div class="w3-panel w3-theme2-l1">w3-theme2-l1</div>
      <div class="w3-panel w3-theme2-d1">w3-theme2-d1</div>
      <div class="w3-panel w3-theme2-d2">w3-theme2-d2</div>
      <div class="w3-panel w3-theme2-d3">w3-theme2-d3</div>
      <div class="w3-panel w3-theme2-d4">w3-theme2-d4</div>
      <div class="w3-panel w3-theme2-d5">w3-theme2-d5</div>
   </div>
   
   <div class="w3-container w3-third">
      <h1>CSS COLORS</h1>
      <div class="w3-panel w3-pale-red">w3-pale-red</div>
      <div class="w3-panel w3-pale-yellow">w3-pale-yellow</div>
      <div class="w3-panel w3-pale-green">w3-pale-green</div>
      <div class="w3-panel w3-pale-blue">w3-pale-blue</div>
      <div class="w3-panel w3-white">w3-white</div>
      <div class="w3-panel w3-black">w3-black</div>
      <div class="w3-panel w3-red">w3-red</div>
      <div class="w3-panel w3-pink">w3-pink</div>
      <div class="w3-panel w3-purple">w3-purple</div>
      <div class="w3-panel w3-deep-purple">w3-deep-purple</div>
      <div class="w3-panel w3-indigo">w3-indigo</div>
      <div class="w3-panel w3-blue">w3-blue</div>
      <div class="w3-panel w3-light-blue">w3-light-blue</div>
      <div class="w3-panel w3-cyan">w3-cyan</div>
      <div class="w3-panel w3-aqua">w3-aqua</div>
      <div class="w3-panel w3-teal">w3-teal</div>
      <div class="w3-panel w3-green">w3-green</div>
      <div class="w3-panel w3-light-green">w3-light-green</div>
      <div class="w3-panel w3-lime">w3-lime</div>
      <div class="w3-panel w3-sand">w3-sand</div>
      <div class="w3-panel w3-khaki">w3-khaki</div>
      <div class="w3-panel w3-yellow">w3-yellow</div>
      <div class="w3-panel w3-amber">w3-amber</div>
      <div class="w3-panel w3-orange">w3-orange</div>
      <div class="w3-panel w3-deep-orange">w3-deep-orange</div>
      <div class="w3-panel w3-blue-grey">w3-blue-grey</div>
      <div class="w3-panel w3-brown">w3-brown</div>
      <div class="w3-panel w3-light-grey">w3-light-grey</div>
      <div class="w3-panel w3-grey">w3-grey</div>
      <div class="w3-panel w3-dark-grey">w3-dark-grey</div>
   </div>

</div>
