<div class="w3-container">
   <?= View::flash().View::Encab($controller_name, $page_action, '') ?>
</div>

<div class="w3-container">
  
  <div class="w3-row-padding w3-center">
    <div class="w3-card-4 w3-dark-grey">
        <h3><?= $MiUsuario->getNombreCompleto() ?></h3>
        <?= $MiUsuario->getFoto(false) ?>
        <h4><?= $MiUsuario->cargo ?></h4>
    </div>
  </div>
  
  <br>
  
  <div class="w3-row-padding w3-center">
    <div class="w3-half w3-dark-grey">
      <br>
      <?php 
        $tabla = new OdaTable();
        $tabla->addRow(['Documento:', $MiUsuario->documento ]);
        $tabla->addRow(['Direccion:', $MiUsuario->direccion ]);
        $tabla->addRow(['Email:', $MiUsuario->email ]);
        $tabla->addRow(['Teléfono(s):', "$MiUsuario->telefono1 $MiUsuario->telefono2" ]);
        $tabla->addRow(['Fecha Nac:', $MiUsuario->fecha_nac ]);
        echo $tabla;
        ?>
      <br>
    </div>

    <div class="w3-half  w3-cell w3-dark-grey">
      <br>
      <?php 
        $tabla = new OdaTable();
        $tabla->addRow( ['Username:', "$MiUsuario->username [$MiUsuario->id]" ]);
        $tabla->addRow( ['MS TEAMS:', $MiUsuario->getCuentaInstit() ]);
        $tabla->addRow( ['Roll:', $MiUsuario->roll ]);
        $tabla->addRow( ['Fecha Ingreso:', $MiUsuario->fecha_ing ]);
        echo $tabla;
        ?>
      <br>
    </div>

  </div>
</div>