<div class="w3-panel">
  <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
  <?= View::flash(); ?>
</div>

<div class="w3-panel">
  <div  class="w3-bar">
    <?php 
    foreach ($data as $key => $salon) {
      echo "<div id=\"btn-$key\"
              onclick=\"traer_data_reg_gen($salon->id, '$salon->nombre', $_annio_actual)\"
              class=\"w3-button w3-bar-item\">
              $salon
            </div>" ;
    }
    ?>
  </div>
  <div id="spinner"><i class="fa fa-spinner w3-spin" style="font-size:32px"></i></div>
  <div id="resultados" class="w3-panel"></div>
</div>

<?= tag::js("dir_grupo/registros/dg_registros_consolidados", false) ?>