<?php 
try {  
  $tabla = new OdaTable('id="myTable-ds" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Desarrollo Psicológico');

  $tabla->addRow( data: [$ModeloAspirPsico->lenguaje ]);
  $tabla->addRow( data: [$ModeloAspirPsico->aprendizaje ]);
  $tabla->addRow( data: [$ModeloAspirPsico->comporta ]);
  $tabla->addRow( data: [$ModeloAspirPsico->afecto ]);
  $tabla->addRow( data: [$ModeloAspirPsico->autocuidado ]);
  $tabla->addRow( data: [$ModeloAspirPsico->especialista ]);
  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
