<?php 
try {  
  $tabla = new OdaTable('id="myTable-m" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos de la Madre');

  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre'), 
      $FormAspir->getInput(field: 'madre_id'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_edad'), 
      $FormAspir->getInput(field: 'madre_prof'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_empresa'), 
      $FormAspir->getInput(field: 'madre_cargo'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_tel_ofi'), 
      $FormAspir->getInput(field: 'madre_tel_per'), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'madre_email'), 
      '', 
      ],
  );

  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
