<?php 
try {  
  $tabla = new OdaTable('id="myTable-ac" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Información sobre Proceso Académico y otros');

  $tabla->addRow( data:[$FormAspirPsico->getDataLabel('proceso_acad') ] );
  $tabla->addRow( data:[$FormAspirPsico->getDataLabel('relpares') ] );
  $tabla->addRow( data:[$FormAspirPsico->getDataLabel('reldocentes') ] );
  $tabla->addRow( data:[$FormAspirPsico->getDataLabel('cumplnormas') ] );
  $tabla->addRow( data:[$FormAspirPsico->getDataLabel('porquedesea') ] );
  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
