<?php 
try {  
  $tabla = new OdaTable('id="myTable-ac" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Información sobre Proceso Académico y otros');

  $tabla->addRow( data:[$ModeloAspirPsico->proceso_acad] );
  $tabla->addRow( data:[$ModeloAspirPsico->relpares] );
  $tabla->addRow( data:[$ModeloAspirPsico->reldocentes] );
  $tabla->addRow( data:[$ModeloAspirPsico->cumplnormas] );
  $tabla->addRow( data:[$ModeloAspirPsico->porquedesea] );
  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
