<?php 
try {  
  $tabla = new OdaTable('id="myTable-p" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos del Padre');

  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre', attrs:''), 
      $FormAspir->getInput(field: 'padre_id', attrs:''), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_edad', attrs:''), 
      $FormAspir->getInput(field: 'padre_prof', attrs:''), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_empresa', attrs:''), 
      $FormAspir->getInput(field: 'padre_cargo', attrs:''), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_tel_ofi', attrs:''), 
      $FormAspir->getInput(field: 'padre_tel_per', attrs:''), 
      ],
  );
  $tabla->addRow(
    data: [
      $FormAspir->getInput(field: 'padre_email', attrs:''), 
      '', 
      ],
    attrs_td: ['colspan="2"'],
  );

  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
