<?php 
try {  
  $tabla = new OdaTable('id="myTable-db" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos del Aspirante');
  
  $tabla->addRow(
    data: [
      '<b>Fecha de Nacimiento:</b><br>'.$ModeloAspirante->fecha_nac, 
      '<b>Tipo de documento:</b><br>'.$ModeloAspirante->tipo_dcto, 
      '<b>Identificación:</b><br>'.$ModeloAspirante->documento, 
    ],
  );

  $tabla->addRow(
    data: [
    '<b>Grado al que Aspira</b><br>'.$ModeloAspirante->grado_aspira, 
    '', 
    '<b>Sexo:</b><br>'.$ModeloAspirante->sexo, 
    ],
  );
  
  $tabla->addRow(
    data: [
      '<b>Pais Nac:</b><br>'.$ModeloAspirante->pais_nac, 
      '<b>Depto Nac:</b><br>'.$ModeloAspirante->depto_nac, 
      '<b>Ciudad Nac:</b><br>'.$ModeloAspirante->ciudad_nac, 
    ],
  );
  
  $tabla->addRow(
    data: [
      '<b>dirección:</b><br>'.$ModeloAspirante->direccion.'<br>'
      .$ModeloAspirante->barrio, 
      '<b>Teléfono:</b><br>'.$ModeloAspirante->telefono1, 
      '',
    ],
    attrs_td: ['colspan="2"'],
  );

  
  $tabla->addRow(
    data: [
      '<b>Relación Actual Padres:</b><br>'.$ModeloAspirPsico->rel_pad_mad, 
      '<b>Personas con las que vive:</b><br>'.$ModeloAspirPsico->vive_con, 
      '', 
      // $FormAspirPsico->getInput(field: 'rel_pad_mad', attrs:''), 
      // $FormAspirPsico->getInput(field: 'vive_con', attrs:'')],
      // 
    ],
    attrs_td: ['','colspan="2"'],
  );

  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
