<?php 
try {  
  $info = '<h2>Historia Escolar</h2><p>Información sobre los últimos Jardines y colegios en los que ha estudiado</p>';

  $tabla = new OdaTable('id="myTable-he1" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 1');
  $tabla->addRow(
    data:[
      // $ModeloAspirante->1_colegio,
      // $ModeloAspirante->1_ciudad,
      // $ModeloAspirante->1_telefono,
    ]
  );

  $tabla->addRow(
    data:[
      // $ModeloAspirante->1_grados,
      // $ModeloAspirante->1_annios,
      // $ModeloAspirante->1_motivo_ret,
    ]
  );
  $info .= $tabla.'<hr>';
  
  $tabla = new OdaTable('id="myTable-he2" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 2');
  $tabla->addRow(
    data:[
      // $ModeloAspirante->2_colegio,
      // $ModeloAspirante->2_ciudad,
      // $ModeloAspirante->2_telefono,
    ]
  );

  $tabla->addRow(
    data:[
      // $ModeloAspirante->2_grados,
      // $ModeloAspirante->2_annios,
      // $ModeloAspirante->2_motivo_ret,
    ]
  );
  $info .= $tabla.'<hr>';
  
  $tabla = new OdaTable('id="myTable-he3" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 3');
  $tabla->addRow(
    data:[
      // $ModeloAspirante->3_colegio,
      // $ModeloAspirante->3_ciudad,
      // $ModeloAspirante->3_telefono,
    ]
  );

  $tabla->addRow(
    data:[
      // $ModeloAspirante->3_grados,
      // $ModeloAspirante->3_annios,
      // $ModeloAspirante->3_motivo_ret,
      ]
  );

  return $tabla.'<hr>';

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
