<?php 
try {  
  $info = '<h2>Historia Escolar</h2><p>Información sobre los últimos Jardines y colegios en los que ha estudiado</p>';
  
  $tabla = new OdaTable('id="myTable-he1" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 1');
  $tabla->addRow(
    data:[
      $FormAspirPsico->getDataLabel('1_colegio'),
      $FormAspirPsico->getDataLabel('1_ciudad'),
      $FormAspirPsico->getDataLabel('1_telefono'),
    ]
  );

  $tabla->addRow(
    data:[
      $FormAspirPsico->getDataLabel('1_grados'),
      $FormAspirPsico->getDataLabel('1_annios'),
      $FormAspirPsico->getDataLabel('1_motivo_ret'),
    ]
  );
  $info .= $tabla.'<hr>';
  
  $tabla = new OdaTable('id="myTable-he2" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 2');
  $tabla->addRow(
    data:[
      $FormAspirPsico->getDataLabel('2_colegio'),
      $FormAspirPsico->getDataLabel('2_ciudad'),
      $FormAspirPsico->getDataLabel('2_telefono'),
    ]
  );

  $tabla->addRow(
    data:[
      $FormAspirPsico->getDataLabel('2_grados'),
      $FormAspirPsico->getDataLabel('2_annios'),
      $FormAspirPsico->getDataLabel('2_motivo_ret'),
    ]
  );
  $info .= $tabla.'<hr>';
  
  $tabla = new OdaTable('id="myTable-he3" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Institución 3');
  $tabla->addRow(
    data:[
      $FormAspirPsico->getDataLabel('3_colegio'),
      $FormAspirPsico->getDataLabel('3_ciudad'),
      $FormAspirPsico->getDataLabel('3_telefono'),
    ]
  );

  $tabla->addRow(
    data:[
      $FormAspirPsico->getDataLabel('3_grados'),
      $FormAspirPsico->getDataLabel('3_annios'),
      $FormAspirPsico->getDataLabel('3_motivo_ret'),
      ]
  );
  $info .= $tabla.'<hr>';

  return $info.'<hr>';

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
