<?php 
try {  
  $tabla = new OdaTable('id="myTable-af" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Antecedentes Familiares');

  $tabla->addRow( data:[ $FormAspirPsico->getDataLabel('nucleofamil' ) ] );
  $tabla->addRow( data:[ $FormAspirPsico->getDataLabel('relpadres' )] );
  $tabla->addRow( data:[ $FormAspirPsico->getDataLabel('rel_pad_mad_desc') ] );
  $tabla->addRow( data:[ $FormAspirPsico->getDataLabel('relhermanos') ] );
  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
