<?php 
try {  
  $tabla = new OdaTable('id="myTable-m" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos de la Madre');

  $tabla->addRow(
    data: [
      $ModeloAspirante->madre, 
      $ModeloAspirante->madre_id, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->madre_edad, 
      $ModeloAspirante->madre_prof, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->madre_empresa, 
      $ModeloAspirante->madre_cargo, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->madre_tel_ofi, 
      $ModeloAspirante->madre_tel_per, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->madre_email, 
      '', 
      ],
  );

  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
