<?php 
try {  
  $tabla = new OdaTable('id="myTable-p" class="w3-table w3-responsive w3-striped w3-bordered"');
  $tabla->setCaption('Datos Básicos del Padre');

  $tabla->addRow(
    data: [
      $ModeloAspirante->padre, 
      $ModeloAspirante->padre_id, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->padre_edad, 
      $ModeloAspirante->padre_prof, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->padre_empresa, 
      $ModeloAspirante->padre_cargo, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->padre_tel_ofi, 
      $ModeloAspirante->padre_tel_per, 
      ],
  );
  $tabla->addRow(
    data: [
      $ModeloAspirante->padre_email, 
      '', 
    ],
  );

  return $tabla;

} catch (\Throwable $th) {
  OdaFlash::error($th);
}
