<div class="w3-panel">
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
   <?= View::flash(); ?>

   <div class="w3-row w3-section">
      <?=OdaForm::inputSearch();?>
   </div>
   
   <?php 
   try {
      $tabla = new OdaTable(theme: $theme, showTotalRegs: true);
      $tabla->setCaption('Lista de Aspirantes Activos');
      $tabla->setHead(
         data_head:    ['id', 'Estado', 'Grado', 'Aspirante', 'Fechas'], 
         attrs:         'class="w3-theme"', 
      );

      foreach($data as $key => $reg) {
         $tabla->addRow(
            data: [
               OdaUtils::fecha_corta($reg->fecha_insc) .'<br>' 
              .$reg->is_active_f(), 
  
               $reg->estatus_f().'<br>'
              .$reg->is_pago_f(),
  
               $reg->aspirante_grado, 
  
               "[$reg->id] ".$reg->lnkPageEditAspiranteSecretaria().
               "<br>Tel: $reg->telefono1 <br>Doc Id: $reg->documento",
  
               "{$reg->ctrl_llamadas_f()} <br> 
                Entrevista: {$reg->fecha_entrev_f()} <br>
                Evaluaci&oacute;n: {$reg->fecha_eval_f()}",   
            ], 
            attrs_td: ['class="searchTdata"', 'class="searchTdata" w3-center', 'class="searchTdata"', 'class="searchTdata"']
         );
      }
      echo $tabla;

    } catch (\Throwable $th) {
      OdaLog::error($th);
      echo $th;
     }

   ?>   
</div>

<?= Tag::js(src: "table_filter"); ?>

<script>
</script>