<?php
  
  // fila #1
  $frm = "<tr class=\"\">";  
  $frm .= OdaTags::createTag(tag: 'td', content: $reg_nota->getFoto(), attrs: 'rowspan="3"');
  $frm .= OdaTags::createTag(tag: 'td', content: $reg_nota->estudiante_nombre."<br>$info_indic", attrs: 'colspan="4"');
  $frm .= OdaTags::createTag(tag: 'td', content: '');
  
  $slider_definitiva = OdaTags::inputRango(id_name: $reg_nota->id, value: $reg_nota->definitiva, min: 0, max: 100, step: 1);
  $field_definitiva = $reg_nota->fieldForm('definitiva');

  $frm .= OdaTags::createTag(tag: 'td', content: $slider_definitiva.'<br>Nota:' . $field_definitiva, attrs: 'colspan="3"');
  $frm .= OdaTags::createTag(tag: 'td', content: 'P.A.<br>'.$reg_nota->plan_apoyo);
  $frm .= OdaTags::createTag(tag: 'td', content: 'N.F.<br>'.$reg_nota->nota_final);
  $frm .= '</tr>';
  

  // reglas para los indicadores
  $patternInidisc  = ' pattern="/^('. implode('|', $arrData['Indicadores']) .')$/"';
  $min_max  = ' min="'.$arrData['min_indic'].'" max="'.$arrData['max_indic'].'" ';
  $max_lenght = ' maxlength="'.strlen(string: $arrData['max_indic']).'" size="'.(strlen(string: $arrData['max_indic'])).'"' ;
  
  // fila #2
  $frm .= "<tr class=\"\">";
  $fields['f2'] = ['i01', 'i02', 'i03', 'i04', 'i05', 'i06', 'i07', 'i08', 'i09', 'i10'];
  foreach ($fields['f2'] as $key => $campo) { 
    $field = $reg_nota->fieldForm($campo, $min_max .$max_lenght .$patternInidisc.' class="color-input"');
    $frm .= OdaTags::createTag(tag:'td', content:$field);
  }//foreach
  $frm .= '</tr>';
  
  // fila #3
  $frm .= "<tr class=\"\">";
  $fields['f3'] = ['i11', 'i12', 'i13', 'i14', 'i15', 'i16', 'i17', 'i18', 'i19', 'i20'];
  foreach ($fields['f3'] as $key => $campo) { 
    $field = $reg_nota->fieldForm($campo, $min_max .$max_lenght .$patternInidisc.' class="color-input"');
    $frm .= OdaTags::createTag(tag:'td', content:$field);
  }//foreach
  $frm .= '</tr>';

  return $frm;
?>
