<?php
  
  // fila #1
  $info_reg = '<br>Reg #'.$Reg->id;
  $frm = "<tr class=\"\">";  
  $frm .= OdaTags::tag(tag: 'td', content: $Reg->getFoto().$info_reg, attrs: 'rowspan="3"');
  $frm .= OdaTags::tag(tag: 'td', content: $Reg->estudiante_nombre."<br>$info_indic", attrs: 'colspan="4"');
  $frm .= OdaTags::tag(tag: 'td', content: '');
  
  $slider_definitiva = OdaTags::inputRango(id_name: $Reg->id, value: $Reg->definitiva, min: 0, max: 100, step: 1);
  $field_definitiva = $Reg->fieldForm('definitiva');
  $field_plan_apoyo = $Reg->fieldForm(field_name: 'plan_apoyo', type:'hidden');
  $field_nota_final = $Reg->fieldForm(field_name: 'nota_final', type:'hidden');

  $las_notas = $field_definitiva.$field_plan_apoyo.$field_nota_final;
  $frm .= OdaTags::tag(tag: 'td', content: $slider_definitiva.'<br>Nota:'.$las_notas, attrs: 'colspan="3"');
  $frm .= OdaTags::tag(tag: 'td', content: 'P.A.<br>'.$Reg->plan_apoyo);
  $frm .= OdaTags::tag(tag: 'td', content: 'N.F.<br>'.$Reg->nota_final);
  $frm .= '</tr>';
  

  // reglas para los indicadores
  $patternInidisc  = ' pattern="/^('. implode('|', $arrData['Indicadores']) .')$/"';
  $min_max  = ' min="'.$arrData['min_indic'].'" max="'.$arrData['max_indic'].'" ';
  $max_lenght = ' maxlength="'.strlen($arrData['max_indic']).'" size="'.(strlen($arrData['max_indic'])).'"' ;
  
  // fila #2
  $frm .= "<tr class=\"\">";
  $fields['f2'] = ['i01', 'i02', 'i03', 'i04', 'i05', 'i06', 'i07', 'i08', 'i09', 'i10'];
  foreach ($fields['f2'] as $key => $campo) { 
    $field = $Reg->fieldForm($campo, $min_max .$max_lenght .$patternInidisc.' class="color-input"');
    $frm .= OdaTags::tag('td', $field);
  }//foreach
  $frm .= '</tr>';
  
  // fila #3
  $frm .= "<tr class=\"\">";
  $fields['f3'] = ['i11', 'i12', 'i13', 'i14', 'i15', 'i16', 'i17', 'i18', 'i19', 'i20'];
  foreach ($fields['f3'] as $key => $campo) { 
    $field = $Reg->fieldForm($campo, $min_max .$max_lenght .$patternInidisc.' class="color-input"');
    $frm .= OdaTags::tag('td', $field);
  }//foreach
  $frm .= '</tr>';

  return $frm;
?>
