<div class="w3-margin-top">

   <?php
      $result = '';
      $tabla = new OdaTable();
      echo OdaForm::inputRango('r1', 'Rango Test', 0, 0, 100, 1);

      foreach ($data as $reg_nota) {
            $registro = require('calificarForm.phtml');
            $registro = $registro;//"<fieldset>$registro</fieldset>";
            $tabla->addRow($registro);
      }
      echo $tabla;
   ?>

</div>

<?= tag::js("tabs_h");?>

<script>
  <?= OdaForm::inputRangoJs('r1') ?>
</script>