<div class="w3-margin-top">

   <?php
      $result = '';
      $tabbuttons = '<div class="w3-bar w3-theme w3-card">';
      foreach ($data as $periodo => $regs_periodo) {
         if (isset($regs_periodo[0])) {
            $tabbuttons .= "<button class=\"w3-bar-item w3-mobile w3-button tablink w3-theme-action\" 
                              onclick=\"openTab(event,'p$periodo')\">Periodo $periodo</button>";
            
            $btn_calificar = OdaTags::linkButton(
              action: "docentes/notasCalificar/$periodo/$Salon->id/$Asignatura->id", 
              text: 'Calificar', 
              icon: '', 
              attrs: 'class="w3-button w3-green w3-round-large"'
            );            
            
            $tabla = new OdaTable();
            $tabla->setCaption("<span>PERIODO $periodo</span> <span>$btn_calificar</span>");

            foreach ($regs_periodo as $key => $nota) {
              $nom_estud = strtoupper(OdaUtils::nombrePersona($nota->estudiante_nombre))
                           ." [$nota->salon_nombre] [$nota->asignatura_nombre]"
                           .'</br>'.$nota->verNota();
                           
              $fila1=array($nota->getFoto(), $nom_estud);
              $t1=($themei=='d'?'d1':'l1');      $t2=($themei=='d'?'d2':'l3');
              $attr = "id=\"$nota->id-1\" class=\"w3-theme-".((($key%2)==0) ? $t1:$t2).'"';
              $attrs_td = array('class="w3-center" rowspan="3"' , 'colspan="10"');
              $tabla->addRow($fila1, $attr, $attrs_td);
               
              $fila2 = array($nota->i01, $nota->i02, $nota->i03, $nota->i04, $nota->i05, 
                             $nota->i06, $nota->i07, $nota->i08, $nota->i09, $nota->i10);
              $attr = "id=\"$nota->id-2\" class=\"w3-theme-".((($key%2)==0) ? $t1:$t2).'"';
              $str = 'style="width:8%"'.str_repeat(',style="width:8%"',9);
              $attrs_td = explode(',',$str);
              $tabla->addRow($fila2, $attr, $attrs_td);
              
              $fila3 = array($nota->i11, $nota->i12, $nota->i13, $nota->i14, $nota->i15, 
                             $nota->i16, $nota->i17, $nota->i18, $nota->i19, $nota->i20);
              $attr = "id=\"$nota->id-3\" class=\"w3-theme-".((($key%2)==0) ? $t1:$t2).'"';
              $tabla->addRow($fila3, $attr, $attrs_td);
            }
            
            $display = ($periodo!=1) ? "style=\"display:none\"" : '' ;
            $result .= "<div id=\"p$periodo\" class=\"tab w3-card-4 w3-padding\" $display >";
            $result .= $tabla;
            $result .= '</div>';
         }
      }
      $tabbuttons .= '</div>';
      echo $tabbuttons.$result;
   ?>

</div>

<?= tag::js("tabs_h");?>