<!doctype html>
<html lang="es">
  <!--begin::Head-->
  <head>
    <!--begin::Primary Meta Tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?=$page_title?></title>
    <meta name="author" content="<?=APP_NAME?>" />
    <meta name="description" content="<?=APP_NAME?>" />
    <meta name="keywords" content="<?=APP_NAME?>" />
    <!--end::Primary Meta Tags-->

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>adminlte3/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?=PUBLIC_PATH?>adminlte3/css/adminlte.min.css">

  <!--end::Head-->
  </head>

  <!--begin::Body-->
  <body class="hold-transition sidebar-mini layout-navbar-fixed">

    <!--begin::App Wrapper-->
    <div class="wrapper">

      <!--begin::Header-->
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <?php View::partial('adminlte3_header') ?>
      </nav>

      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <?php View::partial('adminlte3_aside') ?>
      </aside>

      <!--begin::App Main-->
      <main class="content-wrapper">
        <?=View::content()?>
      </main>
      <!--end::App Main-->

      <!--begin::Footer-->
      <footer class="main-footer">
        <?php View::partial('adminlte3_footer') ?>
      </footer>
      <!--end::Footer-->

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->
      
    </div>
    
    <!--begin::Script-->
    <script src="<?=PUBLIC_PATH?>adminlte3/plugins/jquery/jquery.min.js"></script>
    <script src="<?=PUBLIC_PATH?>adminlte3/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?=PUBLIC_PATH?>adminlte3/js/adminlte.min.js"></script>
    <script src="<?=PUBLIC_PATH?>javascript/htmx2.min.js"></script>
    
  </body>
</html>