<!DOCTYPE html>
<html lang="es">
  
 <head>
  <meta charset=<?=APP_CHARSET?> >
  <title><?=$page_title?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <?= Tag::css('bootstrap5/bootstrap.min') ?>
  <?= Tag::css('fontawesome/css/all.min') ?>
  <?= Html::includeCss() ?>
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <style> html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif} </style>
  
  
  <?= Tag::js('htmx2.min') ?>
  <style>
    .footer-small-text {
        font-size: 0.5rem; /* Tamaño de fuente más pequeño */
    }
  </style>
</head>

<body class="bg-primary-subtle">
  
  <?php View::partial('bs_header','', ['theme'=>"bg-primary-subtle"]) ?>

  <div class="container-fluid">
    <div class="row">

      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <?php View::partial('bs_aside','', ['theme'=>"bg-primary-subtle"]) ?>
          </ul>
          </div>
      </nav>
      
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <?php View::content() ?>
      </main>      
      
    </div>
  </div>
  <footer>
    <?php View::partial('bs_footer','', ['theme'=>'bg-primary-subtle'] ) ?>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"></script>


</body>

</html>