<?php
$data = (array) $data;
if(isset($filename)) {
    header("Content-Disposition: attachment; filename=\"$filename.csv\"");
}
/*mime type para el contenido*/
header('Content-Type: text/csv; charset=utf-8');
/*apertura del buffer de salida*/
$buffer = fopen('php://output', 'w');
// Add UTF-8 BOM for Excel compatibility
fputs($buffer, "﻿");
foreach ($data as $line) {
    fputcsv($buffer, is_object($line) ? get_object_vars($line) : $line, $delimiter ?? ',');
}
fclose($buffer);