<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title><?=$page_title?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Tag::css('w3/w3') ?>
  <?= Tag::css("w3/$theme") ?>
  <?= Tag::css('propios') ?>
  <?= Html::includeCss() ?>
  <script src="https://kit.fontawesome.com/174118a0df.js" crossorigin="anonymous"></script>
  <style> html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif} </style>
</head>

<body class="w3-theme-l4">
  <?php View::partial('header') ?>
  <?php View::partial('aside') ?>

  <div class="w3-main" style="margin-left:250px;margin-top:43px;">      
    <div class="w3-row">
      <div id="list" class="w3-col m4 l4 w3-theme-l3">
        <?php View::content() ?>
      </div>
      <div id="details" class="w3-col m8 l8 w3-theme-d4">
        <ul id="id01">
          <li w3-repeat="customers">{{CustomerName}}</li>
        </ul>
      </div>
    </div>

    <div class="w3-row">
      <?php View::partial('footer') ?>
    </div>
  </div>

<script>
    var mySidebar = document.getElementById("mySidebar"); // Get the Sidebar
    var overlayBg = document.getElementById("myOverlay"); // Get the DIV with overlay effect
    function w3_open() { // Toggle between showing and hiding the sidebar, and add overlay effect
      if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
      } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
      }
    }
    function w3_close() { // Close the sidebar with the close button
      mySidebar.style.display = "none";
      overlayBg.style.display = "none";
    }
</script>

<!-- BEGIN BASE JS -->
<?= Tag::js('jquery/jquery+kumbiaphp.min');?>
<?= Tag::js('bootstrap.bundle.min');?>
<?= Tag::js('jquery/pickadate');?>
<?= Tag::js('w3');?>
</body>

</html>