<div class="w3-bar-block">
   <?= OdaTags::linkBarItem('docen-carga-academica', 'Mi Carga', 'people-line') ?>
   <?= OdaTags::linkBarItem('docen-reg-observaciones', 'Mis Registros', 'address-card') ?>
   <?= OdaTags::linkBarItem('docen-dir-grupo', 'Mi Grupo', 'clipboard') ?>
</div>

<?php if(Session::get('roll')=='coordinadores'): ?>
   <details class="w3-padding">
      <summary> <u>Coordinación</u> </summary>
      <?php View::partial("coordinador/coordinador_menu") ?>
   </details>
<?php endif; ?>