  <h2>Editando Registro</h2>
  <?php
  $model = new RegistrosGen();
  $fieldsToHidden = $model::getFieldsHidden('edit');
  $titulo = '<h3 id="nombre_estud_edit"></h3>';
  $myForm = new OdaForm($model, 'admin/registros_gen/edit_ajax', multipart: true);
    $myForm->setColumnas(2);
    $myForm->setAtrib('id="frm_edit" name="frm_edit"');
    $myForm->addSelect(field:'tipo_reg', columna:1, data: OdaUtils::TIPO_REG_OBSERV);
    $myForm->addSelect(field:'periodo_id', columna:1, data: OdaUtils::PERIODOS);
    $myForm->addInput(field:'fecha', columna:1, tipo:'date');
    $myForm->addTextarea(field:'asunto', columna:1);

    $myForm->addInput(field:'acudiente', columna:2, tipo:'text');
    $myForm->addFile(field:'foto_acudiente', columna:2);
    $myForm->addInput(field:'director', columna:2, tipo:'text');
    $myForm->addFile(field:'foto_director', columna:2);  
    

    $myForm->addHiddens(implode(",", $fieldsToHidden));
    
    return "<div class=\"w3-container\">$titulo $myForm</div>";
  ?>