<?php
    if (count($arrData['estudiantes'])==0) {
      Flash::valid('<h3>Atenci&oacute;n!</h3><p>No hay registros para mostrar.</p>');
    } else {
      echo OdaForm::inputSearch(input_search_id:'inputSearch2', table_id:'mytable2', placeholder:"Filtra por estudiante");
      $tabla = new OdaTable(showTotalRegs: true, _attrs: 'id="myTable2" class="w3-table w3-responsive w3-striped w3-bordered"');
      $tabla->setHead("*Estudiante");
      foreach($arrData['estudiantes'] as $key => $estudiante) {

        $estud = ucwords(OdaUtils::sanearString($estudiante->estudiante_nombre))." $estudiante->salon_nombre [$estudiante->salon_id]";
        $madre = ucwords(OdaUtils::sanearString($estudiante->madre));
        $padre = ucwords(OdaUtils::sanearString($estudiante->padre));
        $info_estud_padres = "$estud<br>Madre: $madre<br>Padre: $padre";
        //de.madre, de.madre_id, de.madre_tel_1, de.madre_email, de.padre, de.padre_id, de.padre_tel_1, de.padre_email

        $data_row = array(
          "<span class=\"w3-btn\" onclick=\"show_new_form('$info_estud_padres', $estudiante->id, $estudiante->grado_id, $estudiante->salon_id, $user_id)\">
          [$estudiante->id]  $estudiante->estudiante_nombre [$estudiante->salon_nombre]</span>"
        );
        $tabla->addRow(data: $data_row, attrs_td:['class="searchTdata"']);
      }
      echo $tabla;
    }//END-IF
?>