<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
</div>

<div class="w3-container w3-row">   
   <div class="w3-threequarter">
      <?php
         if ( isset($data) & (count($data)==0) ) {
            Flash::valid('<h3>Atenci&oacute;n!</h3><p>No hay registros para mostrar.</p>');
         } else {
            require('listHeader.phtml');
            $tabla = new OdaTable(showTotalRegs: true);
            $tabla->setHead("ID, Periodo, Fecha, *Estudiante, *Asunto");
            foreach($data as $key => $reg) {
               $data_row = array(
                  $reg->id,
                  $reg->annio .'-' .$reg->periodo_id,
                  $reg->getFecha('d M'),
                  ucwords(OdaUtils::sanearString($reg->estudiante)),
                  $reg->foto_acudiente.'<br>'.
                  OdaUtils::truncate($reg->asunto, 120)
                    ."<button onclick=\"document.getElementById('$reg->id').style.display='block'\" class=\"w3-btn w3-theme\">ver mas</button>",
                  );
               require 'list_modal.phtml';
               $tabla->addRow(data: $data_row, attrs_td:['','','','class="searchTdata"','class="searchTdata"']);
            } //END-FOR
            echo $tabla;
            require('listFooter.phtml');
         }//END-IF
      ?>
   </div>
   <div class="w3-rest"><?= require 'list_resumen.phtml'; ?></div>
</div>