<?php
  $model = new RegistrosGen;
  $myForm = new OdaForm($model, 'admin/registros_gen/create_ajax', _multipart: true);
    $myForm->setAtrib('id="form_new"');
    $myForm->setColumnas(2);
    $myForm->addSelect(columna:1, field:'periodo_id', data: $model::$periodos);
    $myForm->addInput(columna:1, tipo:'date', field:'fecha', attr:'required');
    $myForm->addInput(columna:1, tipo:'text', field:'asunto', attr:'required');
    $myForm->addInput(columna:1, tipo:'text', field:'acudiente', attr:'required');
    $myForm->addInput(columna:1, tipo:'text', field:'director', attr:'required');
    $myForm->addInput(columna:2, tipo:'file', field:'foto_acudiente', attr:'required');
    $myForm->addInput(columna:2, tipo:'file', field:'foto_director', attr:'required');
  $myForm->addHiddens('uuid, estudiante_id, annio, grado_id, salon_id, created_by, updated_by, created_at, updated_at');

  return "<div class=\"w3-container\" id=\"formulario\" style=\"display: none;\">$myForm</div>";
?>
