<div class="w3-panel">
    <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
    <?php View::flash(); ?>
    <?php 
        //echo OdaUtils::ver_array($RegistrosHist);
        $tabsAnnios = new OdaTabs();
        $ArrAnnios=[];
        foreach ($RegistrosHist as $annio => $regAnnios) {
            $info_periodos = '';
            $tabsPeriodos = new OdaTabs();
            foreach ($regAnnios as $periodo => $regPeriodos) {
                $contenido = '';
                foreach ($regPeriodos as $salon_id => $nomsalon_total) {
                    $Valor = explode(";",$nomsalon_total);
                    $url = "https://windsortemp.schoolnext.space/index.php/+/notasHistoria/GenerarBoletinesHis?annio={$annio}&periodo={$periodo}&salon_id=$salon_id";
                    $contenido .= OdaTags::linkExterno($url, "Descargar $annio - P$periodo : $Valor[0]", ['target'=>'_blank', 'class'=>"w3-btn w3-round-large w3-border w3-border-white"]).'<br>';
                }
                $tabsPeriodos->addTab($annio.$periodo, "$annio P".$periodo, $contenido);
            }
            $ArrAnnios[$annio]=$tabsPeriodos;
        }        
        foreach ($ArrAnnios as $key => $value) {
            echo Tag::create('button', "Boletines del Año $key", ['onclick'=>"acordeon('$key $periodo')", 'class'=>"w3-button w3-block w3-black w3-left-align"]);
            echo "<div id=\"$key $periodo\" class=\"w3-hide w3-container\"><p>$value</p></div>";
        }
    ?>
</div>

<?= tag::js("tabs_h", false);?>
<?= tag::js("acordeon", false);?>