<div class="w3-panel">
  <?= View::Encab($controller_name, $page_action, $breadcrumb); ?>
  <?= View::flash(); ?>
  
  <div class="w3-row">
    <div class="w3-container w3-green w3-mobile">
      <h3 style="text-shadow:1px 1px 0 #444"><i class="fa-solid fa-recycle w3-large"></i> <?= Config::get('config.institution.campania') ?></h3>
    </div>
  </div>

  <div class="w3-row">
    <?php for ($i=1; $i<=4 ; $i++): ?>
      <div class="w3-quarter w3-padding w3-center">
         <div class="w3-card w3-container w3-round-large w3-theme-l3 w3-hover-theme">
            <header class="w3-container">
              <h4 class="w3-left">Indicador #<?=$i?></h>
            </header>
            <p class="w3-left"> <?=_Icons::getAleatorio('w3-xxxlarge')?></p>
            <h3 class="w3-right w3-xxxlarge"><?=random_int(1,99)?>+</h3>
            <footer class="w3-container">
              <h5 class="w3-">Ver +</h5>
            </footer>
         </div>
      </div>
   <?php endfor; ?>
  </div>

  <?= View::partial(partial: 'eventos_dashboard', params: ['data'=>$data]); ?>
  
</div>