<?=$theme=Session::get('theme');?>
<nav class="w3-sidebar w3-collapse w3-theme-<?=$theme?> w3-animate-left" 
     style="z-index:3;width:250px;" id="mySidebar">
  <!-- PERIODO ACADÉMICO Y LOGOUT -->
  <hr/>
  <div class="w3-container w3-row">
      Periodo <?=Session::get('periodo')?> 
      de <?=Session::get('annio')?>
  </div>
  
  <div class="w3-container w3-row">
    [<?=date('M-d',strtotime(Session::get('fecha_inicio')))?> -> <?=date('M-d',strtotime(Session::get('fecha_fin')))?>]
  </div>
  
  <div class="w3-container w3-row">
    [Open: <?=date('M-d',strtotime(Session::get('f_open_day')))?>]
  </div>

  <hr/>
  <!-- USUARIO Y NOTIFICACIONES -->
  <div class="w3-container w3-row">
    <div class="w3-quarter">
      <?= Html::img("ws_leon.png" ,'foto', 'class="w3-circle w3-margin-right" style="width:46px"'); ?>
    </div>
    <div class="w3-auto">
      <?='['.Session::get('id').'] '.Session::get('username').'&nbsp;&nbsp;';?> 
      <?=_Tag::linkIcon('logout', 'arrow-right-from-bracket', 'alt="User Logut"'); ?>
      <br/>
        <span class="w3-hover-text-<?=$theme?>"><?=_Tag::linkIcon('', 'envelope').'&nbsp;'; ?></span>
        <span class="w3-hover-text-<?=$theme?>"><?=_Tag::linkIcon('', 'user-gear').'&nbsp;';?></span>
        <span class="w3-hover-text-<?=$theme?>"><?=_Tag::linkIcon('', 'gear');?></span>
    </div>
    <h5 class="w3-small">
      <br>Ejecutado en <?=round((microtime(1) - $_SERVER['REQUEST_TIME_FLOAT']) * 1000, 4);?> ms
      <br>Usando <?=number_format(memory_get_usage() / 1048576, 3);?> MB <br><br>
</h5>
    
  </div>


  <!-- MENÚ DEL SISTEMA -->
  <div class="w3-bar-block w3-row">
    <a href="/" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" 
    onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>&nbsp; Close Menu</a>
    
    <menu class="w3-padding">
      <?= _Tag::linkBarItem('', 'INICIO') ?>
      <div class="w3-bar-block">
        <?php $modulo = Session::get('modulo'); ?>
        <?php View::partial("$modulo/$modulo"."_menu") ?>
      </div>
      <br><br>
      <?= _Tag::link('index/cambiarTheme', (($theme=='dark') ? 'Modo Claro' : 'Modo Oscuro'), 'class="w3-btn w3-theme"' ) ?>
    </menu>

    
  </div>

</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" 
onclick="w3_close()" 
style="cursor:pointer" 
title="cerrar menú lateral" id="myOverlay">
</div>