<div class="w3-row">
<?php
  $tabla = new OdaTable();
  $tabla->setCaption(caption:'Calendario de Eventos');
  foreach ($data as $key => $value) {
    $hoy = new DateTime();
    $desde = new DateTime($value->fecha_desde);
    $hasta = new DateTime($value->fecha_hasta);

    $pasado  = ($hoy>$hasta) ? 'Pasado' : ''; 
    $vigente = (($hoy>=$desde) and ($hoy<=$hasta)) ? '<b class="w3-yellow">HOY</b>' : '';

    $columna_1 = $desde->format('Y-M-d').'<br> al <br>'.$hasta->format('Y-M-d');
    if ($desde == $hasta) { $columna_1 = $desde->format('Y-M-d'); }
    $columna_2 = $value->nombre;

    $tabla->addRow(data:[$pasado.$vigente, $columna_1, $columna_2], attrs_td:['class="w3-center"']);
  } 
  echo $tabla;
?>
</div>
