<br>
<footer class="w3-panel w3-small w3-center w3-theme">
  <?=Config::get("config.construxzion.name")?><br>
  <?=Config::get("config.construxzion.copy");?><br>
  <?=Config::get("config.construxzion.copy_text");?><br>

  Kumbia PHP: <?=OdaTags::linkExterno('https://github.com/KumbiaPHP/Documentation/tree/master/es', 'KDoc' );?>
  <br>
  MDN: <?=OdaTags::linkExterno('https://developer.mozilla.org/en-US/docs/Web/HTML', 'MDN Html' );?>
  <?=OdaTags::linkExterno('https://developer.mozilla.org/en-US/docs/Web/JavaScript', 'MDN Javascript' );?>
  <br>
  w3School: <?=OdaTags::linkExterno('https://www.w3schools.com/w3css/default.asp', 'w3-CSS');?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/w3js/default.asp', 'w3-JS');?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/js/default.asp', 'w3-Javascript');?>
  <?=OdaTags::linkExterno('https://www.w3schools.com/howto/default.asp', 'HowTO ?' );?>
</footer>
<br>