<?php
require_once VENDOR_PATH. 'autoload.php';
use AdminLTE\Widgets\UserList;

// --- Example Data ---
$img_root = PUBLIC_PATH.'vendor/adminlte/assets/img/';
$users = [
    ['name' => 'Alexander Pierce', 'image' => $img_root.'user1-128x128.jpg', 'meta' => 'Today', 'link' => '#'],
    ['name' => 'Norman', 'image' => $img_root.'/user8-128x128.jpg', 'meta' => 'Yesterday', 'link' => '#'],
    ['name' => 'Jane', 'image' => $img_root.'/user7-128x128.jpg', 'meta' => '12 Jan', 'link' => '#'],
    ['name' => 'John', 'image' => $img_root.'/user6-128x128.jpg', 'meta' => '12 Jan', 'link' => '#'],
    ['name' => 'Alexander', 'image' => $img_root.'/user2-160x160.jpg', 'meta' => '13 Jan', 'link' => '#'],
    ['name' => 'Sarah', 'image' => $img_root.'/user5-128x128.jpg', 'meta' => '14 Jan', 'link' => '#'],
    ['name' => 'Nora', 'image' => $img_root.'/user4-128x128.jpg', 'meta' => '15 Jan', 'link' => '#'],
    ['name' => 'Nadia', 'image' => $img_root.'/user3-128x128.jpg', 'meta' => '15 Jan', 'link' => '#'],
];

$options = [
    'badge_text' => '8 New Members',
    'badge_color' => 'danger',
    'footer_link' => '#'
];

echo UserList::render('Latest Members', $users, $options);
