<div class="w3-container">
   <?= View::flash(); ?>
   <?= View::Encab($controller_name, ucfirst($controller_name). ': '.ucfirst($action_name), ''); ?>
</div>

<div class="w3-container">
  
  <?php
    echo OdaTags::meter(10, 'Titulo');
    echo _Icons::solid('flag', 'w3-xxxlarge');

    list($id, $name, $value) = array(1,2,3);
    echo $id.'-'.$name.'-'.$value;

    $array = ['locality' => 'Tunis', 'postal_code' => '1110'];
    list('postal_code' => $zipCode, 'locality' => $locality) = $array;
    print $zipCode; // will output 1110
    print $locality; // will output Tunis

    $names = array('Jesse', 'joey', 'jelnny', 'justine');
    $names = new ArrayObject($names);

    echo '<pre>';
      print_r($names);
    echo '</pre>';

    $tabla = new OdaTable();
    $tabla->setHead('col 1, col 2, col 3')
          ->addRow('data 1-1, col 1-2, col 1-3')
          ->addRow('data 2-1, col 2-2, col 2-3')
          ->addRow('data 3-1, col 3-2, col 3-3')
          ->setFoot(['--', 'Fin', '--']);
    echo $tabla;
   ?>

</div>