<table id="producttable">
  <thead>
    <tr>
      <td>UPC_Code</td>
      <td>Product_Name</td>
    </tr>
  </thead>
  <tbody>
    <!-- datos opcionales pueden incluirse aquí opcionalmente -->
  </tbody>
</table>

<template id="productrow">
  <tr>
    <td class="record"></td>
    <td></td>
  </tr>
</template>

<script>
  // Comprobar si el navegador soporta el elemento HTML template element chequeando
// si tiene el atributo 'content'
if ('content' in document.createElement('template')) {

// Instanciar la tabla con el tbody existente
// y la fila con el template
var template = document.querySelector('#productrow');
td = template.content.querySelectorAll("td");
td[0].textContent = "1235646565";
td[1].textContent = "Stuff";

// Clonar la nueva fila e insertarla en la tabla
var tablebody = document.querySelector("tbody");
var clone = document.importNode(template.content, true);
tablebody.appendChild(clone);

// Crear una nueva fila
td[0].textContent = "0384928528";
td[1].textContent = "Acme Kidney Beans";

// Clonar la nueva fila e insertarla en la tabla
var clone2 = document.importNode(template.content, true);
tablebody.appendChild(clone2);

} else {
// Buscar otra manera de añadir filas a la tabla porque el
// elemento template no está soportado.
}
</script>