<div class="w3-bar-block">
   <?php
      echo _Tag::linkBarItem('secre-estud-list-activos', 'E. Activos', 'person-circle-check');
      echo _Tag::linkBarItem('secre-estud-list-inactivos', 'E. Inactivos', 'person-circle-xmark');

/*       $breadcrumb = new Breadcrumb();
        $breadcrumb->class_ul = 'w3-bar-block';
        $breadcrumb->separator='';
        $breadcrumb->class_separator='w3-bar-item';
        $breadcrumb->addCrumb(0, '&#127968;');
        $breadcrumb->addCrumb(1, 'E. Activos', 'secretaria/listadoEstudActivos');
        $breadcrumb->addCrumb(2, 'E. Inactivos', 'secretaria/listadoEstudInactivos');
      echo $breadcrumb->display(); */
   ?>
</div>
