<div class="w3-bar-block">
   <?php
      echo OdaTags::linkBarItem('secretaria/listadoEstudActivos', 'E. Activos', 'person-circle-check');
      echo OdaTags::linkBarItem('secretaria/listadoEstudInactivos', 'E. Inactivos', 'person-circle-xmark');
      echo OdaTags::linkBarItem('secre-admisiones', 'Admisiones', 'person-walking-arrow-right');
      echo OdaTags::linkBarItem('secre-historico-notas', 'Históricos', 'timeline');
   ?>
</div>
