<div id="scaffold">
	<?php View::content()?>

	<div class="actions">
		<a href="../">Volver a Listado</a>
		<a href="../crear/">Crear registro</a>
	</div>

	<?php if ($data) : ?>
		<h1><?= ucwords("$model"),": <span>$action_name</span>" ?></h1>
		<ul>
		<?php foreach ($data as $nombre_campo => $valor_campo) : ?>
			<li> <strong><?= $data->getLabel($nombre_campo) ?> :</strong>  <?= $valor_campo ?></li>
		<?php endforeach ?>
		</ul>
		<div class="actions">
			<a href="../editar/<?= $data->id?>" class="btn btn-warning">Editar</a>
			<a class="del btn btn-danger" title="¿Seguro que quiere borrar?" href="../borrar/<?= $data->id?>" onclick="return confirm('¿Está seguro?');">Borrar</a>
		</div>
	<?php else : ?>
		<?php http_response_code(404)?>
		<h1>Usuario No existe</h1>
	<?php endif ?>
</div>
